// Sony Values

package sony

// enumValues holds every value enum the SDK header defines.
var enumValues = map[string]map[uint64]string{
	"CrAFAssist": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAFIlluminator": {
		0x1: "Off",
		0x2: "Auto",
	},
	"CrAFInFocusMagnifier": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAFTrackForSpeedChange": {
		0x1: "Stable",
		0x2: "Standard",
		0x3: "Responsive",
	},
	"CrAFTrackingSensitivity": {
		0x1: "1",
		0x2: "2",
		0x3: "3",
		0x4: "4",
		0x5: "5",
	},
	"CrAFWithShutter": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAPS_C_S35": {
		0x1: "Off",
		0x2: "On",
		0x3: "Auto",
	},
	"CrAPS_C_or_Full_SwitchingEnableStatus": {
		0x0: "Switching_Disable",
		0x1: "Switching_Enable",
	},
	"CrAPS_C_or_Full_SwitchingSetting": {
		0x1: "Full",
		0x2: "APS_C",
	},
	"CrAWB": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrAntidustShutterWhenPowerOff": {
		0x1: "Off",
		0x2: "On",
	},
	"CrApertureDriveInAF": {
		0x1: "Standard",
		0x2: "FocusPriority",
		0x3: "SilentPriority",
	},
	"CrAspectMarkerRatioMovie": {
		0x1:  "Off",
		0x2:  "9x16",
		0x3:  "4x5",
		0x4:  "1x1",
		0x5:  "4x3",
		0x6:  "13x9",
		0x7:  "14x9",
		0x8:  "15x9",
		0x9:  "16x9",
		0xA:  "17x9",
		0xB:  "1_66x1",
		0xC:  "1_85x1",
		0xD:  "1_91x1",
		0xE:  "2x1",
		0xF:  "2_35x1",
		0x10: "2_39x1",
	},
	"CrAspectRatioIndex": {
		0x1: "AspectRatio_3_2",
		0x2: "AspectRatio_16_9",
		0x3: "AspectRatio_4_3",
		0x4: "AspectRatio_1_1",
	},
	"CrAssignableButton": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrAssignableButtonIndicator": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAudioInputCHInputSelect": {
		0x1: "Off",
		0x2: "INPUT1",
		0x3: "INPUT2",
		0x4: "InternalMIC",
		0x5: "ShoeCH1",
		0x6: "ShoeCH2",
		0x7: "StereoMicJackL",
		0x8: "StereoMicJackR",
	},
	"CrAudioInputCHLevelControl": {
		0x1: "Auto",
		0x2: "Manual",
	},
	"CrAudioInputCHWindFilter": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAudioInputTypeSelect": {
		0x1: "MIC",
		0x2: "LINE",
	},
	"CrAudioLevelDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAudioRecording": {
		0x0: "Off",
		0x1: "On",
	},
	"CrAudioSignals": {
		0x1: "Off",
		0x2: "On",
		0x3: "OnShutterOnly",
		0x4: "OnWithoutShutter",
	},
	"CrAudioSignalsStartEnd": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAudioStreamBitDepth": {
		0x1: "16bit",
		0x2: "24bit",
		0x3: "32bit",
	},
	"CrAudioStreamChannel": {
		0x1: "1ch",
		0x2: "2ch",
		0x4: "4ch",
	},
	"CrAudioStreamCodecType": {
		0x20: "AACLC",
	},
	"CrAutoFocusHold": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAutoPowerOffTemperature": {
		0x1: "Standard",
		0x2: "High",
	},
	"CrAutoRecognitionTargetCandidate": {
		0x1:  "Person",
		0x2:  "Animal",
		0x4:  "Bird",
		0x8:  "Insect",
		0x10: "CarTrain",
		0x20: "Plane",
	},
	"CrAutoReview": {
		0x0: "Off",
	},
	"CrAutoSlowShutter": {
		0x1: "Off",
		0x2: "On",
	},
	"CrAutoSwitchMedia": {
		0x1: "Off",
		0x2: "On",
	},
	"CrBaseLookAppliedofPlayback": {
		0x1: "Applicable",
		0x2: "Not_Applicable",
	},
	"CrBaseLookImportOperationEnableStatus": {
		0x0: "BaseLookImportOperation_Disable",
		0x1: "BaseLookImportOperation_Enable",
	},
	"CrBaseLookNumber": {
		0x1:  "1",
		0x2:  "2",
		0x3:  "3",
		0x4:  "4",
		0x5:  "5",
		0x6:  "6",
		0x7:  "7",
		0x8:  "8",
		0x9:  "9",
		0xA:  "10",
		0xB:  "11",
		0xC:  "12",
		0xD:  "13",
		0xE:  "14",
		0xF:  "15",
		0x10: "16",
	},
	"CrBaseLookValueSetter": {
		0x0:  "BaseLookValue_Preset",
		0x1:  "BaseLookValue_User",
		0x80: "BaseLookValue_Temporary",
		0x2:  "BaseLookValue_Scene",
	},
	"CrBatteryLevel": {
		0x1:        "PreEndBattery",
		0x2:        "1_4",
		0x3:        "2_4",
		0x4:        "3_4",
		0x5:        "4_4",
		0x6:        "1_3",
		0x7:        "2_3",
		0x8:        "3_3",
		0x10000:    "USBPowerSupply",
		0x10001:    "PreEnd_PowerSupply",
		0x10002:    "1_4_PowerSupply",
		0x10003:    "2_4_PowerSupply",
		0x10004:    "3_4_PowerSupply",
		0x10005:    "4_4_PowerSupply",
		0xFFFFFFFD: "Fake",
		0xFFFFFFFE: "BatteryNotInstalled",
	},
	"CrBatteryRemainDisplayUnit": {
		0x1: "minute",
		0x2: "percent",
		0x3: "voltage",
	},
	"CrBodyKeyLock": {
		0x1: "BodyKey_Unlock",
		0x2: "BodyKey_Lock",
	},
	"CrBracketOrder": {
		0x1: "0ToMinusToPlus",
		0x2: "MinusTo0ToPlus",
	},
	"CrBulbTimerSetting": {
		0x0: "Off",
		0x1: "On",
	},
	"CrCallSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrCameraButtonFunction": {
		0x10000:  "UpButton",
		0x20000:  "DownButton",
		0x30000:  "LeftButton",
		0x40000:  "RightButton",
		0x50000:  "EnterButton",
		0x60000:  "MenuButton",
		0x70000:  "MultiSelectorUp",
		0x80000:  "MultiSelectorDown",
		0x90000:  "MultiSelectorLeft",
		0xA0000:  "MultiSelectorRight",
		0xB0000:  "MultiSelectorEnter",
		0xC0000:  "MultiSelectorRightUp",
		0xD0000:  "MultiSelectorRightDown",
		0xE0000:  "MultiSelectorLeftUp",
		0xF0000:  "MultiSelectorLeftDown",
		0x100000: "FnButton",
		0x110000: "PlaybackButton",
		0x120000: "DeleteButton",
		0x130000: "ModeButton",
		0x140000: "C1Button",
		0x150000: "C2Button",
		0x160000: "C3Button",
		0x170000: "C4Button",
		0x180000: "C5Button",
		0x190000: "C6Button",
		0x1A0000: "MovieButton",
		0x1B0000: "AELButton",
		0x1C0000: "AFOnButton",
		0x1D0000: "HomeButton",
		0x1E0000: "ClipsButton",
		0x1F0000: "SlotSelectButton",
		0x200000: "DisplayButton",
		0x210000: "C7Button",
		0x220000: "CancelBackButton",
		0x230000: "ThumbnailButton",
	},
	"CrCameraButtonFunctionStatus": {
		0x1: "Idle",
		0x2: "AnyKeyOn",
	},
	"CrCameraButtonFunctionValue": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrCameraDialFunction": {
		0x40010000: "ControlWheel",
		0x40020000: "FrontDial",
		0x40030000: "RearDialL",
		0x40040000: "RearDialR",
	},
	"CrCameraEframing": {
		0x1: "Off",
		0x2: "On",
	},
	"CrCameraErrorCautionStatus": {
		0x1: "NoError",
		0x2: "Error",
	},
	"CrCameraLeverFunction": {
		0x50010000: "TeleWideLever",
	},
	"CrCameraOperatingMode": {
		0x1: "Record",
		0x2: "Playback",
	},
	"CrCameraPowerStatus": {
		0x1: "Off",
		0x2: "Standby",
		0x3: "PowerOn",
		0x4: "TransitioningFromPowerOnToStandby",
		0x5: "TransitioningFromStandbyToPowerOn",
	},
	"CrCameraSettingReadOperation": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrCameraSettingSaveOperation": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrCameraSettingSaveReadState": {
		0x0: "Idle",
		0x1: "Reading",
	},
	"CrCameraSettingsResetEnableStatus": {
		0x0: "CameraSettingsReset_Disable",
		0x1: "CameraSettingsReset_Enable",
	},
	"CrCameraShakeStatus": {
		0x1: "NoError",
		0x2: "Error",
	},
	"CrCancelContentsTransferEnableStatus": {
		0x0: "CancelContentsTransfer_Disable",
		0x1: "CancelContentsTransfer_Enable",
	},
	"CrCancelMediaFormat": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrCancelRemoteTouchOperationEnableStatus": {
		0x0: "CancelRemoteTouchOperation_Disable",
		0x1: "CancelRemoteTouchOperation_Enable",
	},
	"CrCenterMarkerDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrCinematicVlogAFTransitionSpeed": {
		0x1: "High",
		0x2: "Middle",
		0x3: "Low",
	},
	"CrCinematicVlogLook": {
		0x1:   "Classic",
		0x2:   "S_Cinetone",
		0x3:   "Clean",
		0x4:   "Chic",
		0x5:   "Fresh",
		0x6:   "Mono",
		0x101: "User1",
		0x102: "User2",
		0x103: "User3",
		0x104: "User4",
		0x105: "User5",
		0x106: "User6",
		0x107: "User7",
		0x108: "User8",
		0x109: "User9",
		0x10A: "User10",
		0x10B: "User11",
		0x10C: "User12",
		0x10D: "User13",
		0x10E: "User14",
		0x10F: "User15",
		0x110: "User16",
	},
	"CrCinematicVlogMood": {
		0x1: "Auto",
		0x2: "Gold",
		0x3: "Ocean",
		0x4: "Forest",
	},
	"CrCinematicVlogSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrColorSpace": {
		0x1: "SRGB",
		0x2: "AdobeRGB",
	},
	"CrColorTuning": {
		0x0:  "Min",
		0xFF: "Max",
	},
	"CrColortemp": {
		0x0:    "Min",
		0xFFFF: "Max",
	},
	"CrCompRAWShootingHDRDRSetting": {
		0x1:  "Level1",
		0x2:  "Level2",
		0x3:  "Level3",
		0x80: "AUTO",
	},
	"CrCompRAWShootingMode": {
		0x1: "CompRAWShooting_Off",
		0x2: "CompRAWShooting_On",
	},
	"CrCompRAWShootingNumberOfSheets": {
		0x0: "Invalid",
	},
	"CrCompressionFileFormat": {
		0x1: "JPEG",
		0x2: "HEIF_422",
		0x3: "HEIF_420",
	},
	"CrContentsFile_AspectRatio": {
		0x0: "Unspecified",
		0x1: "4_3",
		0x2: "16_9",
		0x3: "3_2",
		0x4: "1_1",
		0x5: "17_9",
		0x6: "256_135",
	},
	"CrContentsFile_AudioCodec": {
		0x0:   "Unspecified",
		0x1:   "LinearPcm",
		0x2:   "LinearPcmFloat",
		0x180: "AacLc",
	},
	"CrContentsFile_ColorFormat": {
		0x0:  "Unspecified",
		0x1:  "YCbCr420",
		0x2:  "YCbCr411",
		0x3:  "YCbCr422",
		0x11: "RGB444",
		0x12: "RGBA4444",
	},
	"CrContentsFile_FileFormat": {
		0x0:    "Unspecified",
		0x3801: "Jpeg",
		0xB101: "Raw",
		0xB110: "Heif",
		0x3008: "Wav",
		0xB982: "Mp4",
		0xBA82: "Xml",
	},
	"CrContentsFile_GopStructure": {
		0x0: "Unspecified",
		0x1: "LongGop",
		0x2: "IntraFrame",
	},
	"CrContentsFile_NumberOfChannels": {
		0x0:  "Unspecified",
		0x10: "Mono",
		0x20: "Stereo",
		0x21: "2_1_Channels",
		0x30: "3_Channels",
		0x31: "3_1_Channels",
		0x40: "4_Channels",
		0x41: "4_1_Channels",
		0x50: "5_Channels",
		0x51: "5_1_Channels",
		0x52: "5_2_Channels",
		0x60: "6_Channels",
		0x61: "6_1_Channels",
		0x62: "6_2_Channels",
		0x70: "7_Channels",
		0x71: "7_1_Channels",
		0x72: "7_2_Channels",
		0x80: "8_Channels",
		0x81: "8_1_Channels",
		0x82: "8_2_Channels",
		0x90: "9_Channels",
		0x91: "9_1_Channels",
		0x92: "9_2_Channels",
	},
	"CrContentsFile_ProfileIndication": {
		0x1: "High",
		0x2: "Main",
		0x3: "StereoHigh",
		0x4: "High422",
		0x5: "Main10",
		0x6: "Main422_10",
	},
	"CrContentsFile_Rdd18metaCaptureGammaEquation": {
		0x0:    "CaptureGammaEquation_Unspecified",
		0x1:    "CaptureGammaEquation_Cine1",
		0x2:    "CaptureGammaEquation_Cine2",
		0x3:    "CaptureGammaEquation_Cine3",
		0x4:    "CaptureGammaEquation_Cine4",
		0x21:   "CaptureGammaEquation_SLog",
		0x24:   "CaptureGammaEquation_R709_800per",
		0x28:   "CaptureGammaEquation_SLog2",
		0x30:   "CaptureGammaEquation_ReproducedUnknownLabel",
		0x35:   "CaptureGammaEquation_ItuRRecBt709",
		0x49:   "CaptureGammaEquation_UserDefinedCurve9",
		0x51:   "CaptureGammaEquation_NxcamStandard",
		0x52:   "CaptureGammaEquation_NxcamStillCameraLike",
		0x53:   "CaptureGammaEquation_Xvycc",
		0x54:   "CaptureGammaEquation_SLog3_SGamut3",
		0x55:   "CaptureGammaEquation_SLog3_SGamut3Cine",
		0x56:   "CaptureGammaEquation_ItuRRecBt2020",
		0x58:   "CaptureGammaEquation_ItuRRecBt2100HybridLogGamma",
		0x61:   "CaptureGammaEquation_NxcamCinematone1",
		0x62:   "CaptureGammaEquation_NxcamCinematone2",
		0xF000: "CaptureGammaEquation_StillsRgb",
		0xFFFF: "CaptureGammaEquation_InvalidValue",
	},
	"CrContentsFile_Rdd18metaCodingEquations": {
		0x0:    "CodingEquations_DeterminedByColorPrimariesProperties",
		0x1:    "CodingEquations_ItuRRecBt601CodingEquations",
		0x2:    "CodingEquations_ItuRRecBt709CodingEquations",
		0x5:    "CodingEquations_ItuRRecBt2020NonConstantLuminunce",
		0xF:    "CodingEquations_UnknownStandard",
		0xF000: "CodingEquations_StillsRgb",
		0xFFFF: "CodingEquations_InvalidValue",
	},
	"CrContentsFile_Rdd18metaColorPrimaries": {
		0x0:    "ColorPrimaries_DeterminedByTheOtherProperties",
		0x31:   "ColorPrimaries_ItuRBtRec709ColorPrimaries",
		0x32:   "ColorPrimaries_ItuRBtRec2020ColorPrimaries",
		0x33:   "ColorPrimaries_SonyGamutForSLog",
		0x34:   "ColorPrimaries_SonyGamut3ForSLog3",
		0x35:   "ColorPrimaries_SonyGamut3forR709_DciP3",
		0x3F:   "ColorPrimaries_UnknownStandard",
		0xF000: "ColorPrimaries_StillsRgb",
		0xFFFF: "ColorPrimaries_InvalidValue",
	},
	"CrContentsFile_ScanType": {
		0x0: "Unspecified",
		0x1: "Interlace",
		0x2: "Progressive",
		0x3: "PseudoProgressive",
		0x4: "RealProgressive",
	},
	"CrContentsFile_VideoCodec": {
		0x0:        "Unspecified",
		0x48323634: "Avc",
		0x48323635: "Hevc",
	},
	"CrContentsInfoListEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrContentsInfo_ContentType": {
		0x0:  "Unspecified",
		0x1:  "Dcf",
		0x4:  "M4style",
		0x8:  "Xdstyle",
		0x10: "Pxstyle",
	},
	"CrContentsInfo_GroupType": {
		0x0: "Unspecified",
		0x1: "Continuation",
		0x2: "Timelapse",
		0x3: "Bracket",
	},
	"CrContentsInfo_Rating": {
		0xFFFFFFFFFFFFFFFF: "NotRequired",
		0x0:                "Nothing",
		0x1:                "1",
		0x2:                "2",
		0x3:                "3",
		0x4:                "4",
		0x5:                "5",
	},
	"CrContentsTransferStatus": {
		0x0: "ContentsTransfer_OFF",
		0x1: "ContentsTransfer_ON",
	},
	"CrContinuousShootingSpeedInElectricShutter": {
		0x0: "Invalid",
	},
	"CrContinuousShootingSpotBoostEnableStatus": {
		0x1: "ContinuousShootingSpotBoost_Disable",
		0x2: "ContinuousShootingSpotBoost_Enable",
	},
	"CrContinuousShootingSpotBoostStatus": {
		0x1: "NotSpotBoosting",
		0x2: "SpotBoosting",
	},
	"CrControlForHDMI": {
		0x1: "Off",
		0x2: "On",
	},
	"CrControlGeneralSettingFileEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrCreateNewFolderEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrCreativeLook": {
		0x1:   "ST",
		0x2:   "PT",
		0x3:   "NT",
		0x4:   "VV",
		0x5:   "VV2",
		0x6:   "FL",
		0x7:   "IN",
		0x8:   "SH",
		0x9:   "BW",
		0xA:   "SE",
		0xB:   "Film2",
		0xC:   "Film3",
		0x100: "CustomLookOffset",
	},
	"CrCreativeLookResetEnableStatus": {
		0x0: "CreativeLookReset_Disable",
		0x1: "CreativeLookReset_Enable",
	},
	"CrCurrentSceneFileEdited": {
		0x1: "Unedited",
		0x2: "Edited",
	},
	"CrCustomWBSizeSetting": {
		0x1: "S",
		0x2: "M",
		0x3: "L",
	},
	"CrDRangeOptimizer": {
		0x0:  "Off",
		0x1:  "On",
		0x10: "Plus",
		0x11: "Plus_Manual_1",
		0x12: "Plus_Manual_2",
		0x13: "Plus_Manual_3",
		0x14: "Plus_Manual_4",
		0x15: "Plus_Manual_5",
		0x16: "Plus_Manual_6",
		0x17: "Plus_Manual_7",
		0x18: "Plus_Manual_8",
		0x20: "Auto",
		0x30: "HDR_Auto",
		0x31: "HDR_10Ev",
		0x32: "HDR_20Ev",
		0x33: "HDR_30Ev",
		0x34: "HDR_40Ev",
		0x35: "HDR_50Ev",
		0x36: "HDR_60Ev",
		0x80: "ExtendedOffset",
	},
	"CrDaylightSavings": {
		0x0: "Off",
		0x1: "On",
	},
	"CrDebugMode": {
		0x1: "OFF",
		0x2: "Pseudo_update_with_Fake_Firmware",
	},
	"CrDeleteContentOperationEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrDeleteUserBaseLook": {
		0x0:    "Invalid",
		0xFFFF: "All",
	},
	"CrDepthOfFieldAdjustmentInterlockingMode": {
		0x1: "NDInterlockingMode",
		0x2: "GainInterlockingMode",
	},
	"CrDepthOfFieldAdjustmentMode": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrDeviceOverheatingState": {
		0x0: "NotOverheating",
		0x1: "PreOverheating",
		0x2: "Overheating",
	},
	"CrDifferentSetForSQMovie": {
		0x1: "On_Different",
		0x2: "Off_Identical",
	},
	"CrDispMode": {
		0x1: "GraphicDisplay",
		0x2: "DisplayAllInfo",
		0x3: "NoDispInfo",
		0x4: "Histogram",
		0x5: "Level",
		0x6: "ForViewFinder",
		0x7: "MonitorOff",
		0x8: "HistogramAndLevel",
	},
	"CrDispModeBitNum": {
		0x1:   "GraphicDisplay",
		0x2:   "DisplayAllInfo",
		0x4:   "Histogram",
		0x8:   "Level",
		0x10:  "NoDispInfo",
		0x20:  "NoDispInfoExposureOn",
		0x40:  "NoDispInfoExposureTimeOut",
		0x80:  "ForViewFinder",
		0x100: "MonitorOff",
		0x200: "HistogramAndLevel",
	},
	"CrDisplayQuality": {
		0x1: "Standard",
		0x2: "High",
	},
	"CrDisplayQualityFinder": {
		0x1: "Standard",
		0x2: "High",
	},
	"CrDisplayStringType": {
		0x0:  "AllList",
		0x1:  "BaseLook_AELevelOffset_ExposureValue",
		0x2:  "BaseLook_Input_Display",
		0x3:  "BaseLook_Name_Display",
		0x4:  "BaseLook_Output_Display",
		0x5:  "SceneFile_Name_Display",
		0x6:  "ShootingMode_Cinema_ColorGamut_Display",
		0x7:  "ShootingMode_TargetDisplay_Display",
		0x8:  "Camera_Gain_BaseISO_Display",
		0x9:  "Video_EIGain_Display",
		0xA:  "Button_Assign_Display",
		0xB:  "Button_Assign_ShortDisplay",
		0xC:  "FTP_ServerName_Display",
		0xD:  "FTP_UpLoadDirectory_Display",
		0xE:  "FTP_JobStatus_Display",
		0xF:  "ExposureIndex_Preset1_Display",
		0x10: "Reserved5",
		0x11: "Reserved6",
		0x12: "Reserved7",
		0x13: "CreativeLook_Name_Display",
		0x14: "IPTC_Metadata_Display",
		0x15: "SubjectRecognitionAF_Display",
		0x16: "BaseLook_MetaRecordSupport_Display",
		0x17: "Target_StreamingDestinationSelect_Display",
		0x18: "Camera_Button_Function_Capability_Display",
		0x19: "Camera_Lever_Function_Capability_Display",
		0x1A: "Camera_Dial_Function_Capability_Display",
		0x1B: "CustomGridLine_FileName_Display",
	},
	"CrDisplayedMenuStatus": {
		0x1: "Off",
		0x2: "StatusMenu",
		0x3: "FullMenu",
	},
	"CrDownloadSettingFileType": {
		0x0:        "Setup",
		0x2:        "FTPTransferSetting",
		0x3:        "SceneFile",
		0xFFFFFFFF: "None",
	},
	"CrDriveMode": {
		0x1:        "Drive_Single",
		0x10001:    "Drive_Continuous_Hi",
		0x10002:    "Drive_Continuous_Hi_Plus",
		0x10003:    "Drive_Continuous_Hi_Live",
		0x10004:    "Drive_Continuous_Lo",
		0x10005:    "Drive_Continuous",
		0x10006:    "Drive_Continuous_SpeedPriority",
		0x10007:    "Drive_Continuous_Mid",
		0x10008:    "Drive_Continuous_Mid_Live",
		0x10009:    "Drive_Continuous_Lo_Live",
		0x11001:    "Drive_SingleBurstShooting_lo",
		0x11002:    "Drive_SingleBurstShooting_mid",
		0x11003:    "Drive_SingleBurstShooting_hi",
		0x12001:    "Drive_FocusBracket",
		0x20001:    "Drive_Timelapse",
		0x30001:    "Drive_Timer_2s",
		0x30002:    "Drive_Timer_5s",
		0x30003:    "Drive_Timer_10s",
		0x40301:    "Drive_Continuous_Bracket_03Ev_3pics",
		0x40302:    "Drive_Continuous_Bracket_03Ev_5pics",
		0x40303:    "Drive_Continuous_Bracket_03Ev_9pics",
		0x40304:    "Drive_Continuous_Bracket_05Ev_3pics",
		0x40305:    "Drive_Continuous_Bracket_05Ev_5pics",
		0x40306:    "Drive_Continuous_Bracket_05Ev_9pics",
		0x40307:    "Drive_Continuous_Bracket_07Ev_3pics",
		0x40308:    "Drive_Continuous_Bracket_07Ev_5pics",
		0x40309:    "Drive_Continuous_Bracket_07Ev_9pics",
		0x4030A:    "Drive_Continuous_Bracket_10Ev_3pics",
		0x4030B:    "Drive_Continuous_Bracket_10Ev_5pics",
		0x4030C:    "Drive_Continuous_Bracket_10Ev_9pics",
		0x4030D:    "Drive_Continuous_Bracket_20Ev_3pics",
		0x4030E:    "Drive_Continuous_Bracket_20Ev_5pics",
		0x4030F:    "Drive_Continuous_Bracket_30Ev_3pics",
		0x40310:    "Drive_Continuous_Bracket_30Ev_5pics",
		0x40311:    "Drive_Continuous_Bracket_03Ev_2pics_Plus",
		0x40312:    "Drive_Continuous_Bracket_03Ev_2pics_Minus",
		0x40313:    "Drive_Continuous_Bracket_03Ev_7pics",
		0x40314:    "Drive_Continuous_Bracket_05Ev_2pics_Plus",
		0x40315:    "Drive_Continuous_Bracket_05Ev_2pics_Minus",
		0x40316:    "Drive_Continuous_Bracket_05Ev_7pics",
		0x40317:    "Drive_Continuous_Bracket_07Ev_2pics_Plus",
		0x40318:    "Drive_Continuous_Bracket_07Ev_2pics_Minus",
		0x40319:    "Drive_Continuous_Bracket_07Ev_7pics",
		0x4031A:    "Drive_Continuous_Bracket_10Ev_2pics_Plus",
		0x4031B:    "Drive_Continuous_Bracket_10Ev_2pics_Minus",
		0x4031C:    "Drive_Continuous_Bracket_10Ev_7pics",
		0x4031D:    "Drive_Continuous_Bracket_13Ev_2pics_Plus",
		0x4031E:    "Drive_Continuous_Bracket_13Ev_2pics_Minus",
		0x4031F:    "Drive_Continuous_Bracket_13Ev_3pics",
		0x40320:    "Drive_Continuous_Bracket_13Ev_5pics",
		0x40321:    "Drive_Continuous_Bracket_13Ev_7pics",
		0x40322:    "Drive_Continuous_Bracket_15Ev_2pics_Plus",
		0x40323:    "Drive_Continuous_Bracket_15Ev_2pics_Minus",
		0x40324:    "Drive_Continuous_Bracket_15Ev_3pics",
		0x40325:    "Drive_Continuous_Bracket_15Ev_5pics",
		0x40326:    "Drive_Continuous_Bracket_15Ev_7pics",
		0x40327:    "Drive_Continuous_Bracket_17Ev_2pics_Plus",
		0x40328:    "Drive_Continuous_Bracket_17Ev_2pics_Minus",
		0x40329:    "Drive_Continuous_Bracket_17Ev_3pics",
		0x4032A:    "Drive_Continuous_Bracket_17Ev_5pics",
		0x4032B:    "Drive_Continuous_Bracket_17Ev_7pics",
		0x4032C:    "Drive_Continuous_Bracket_20Ev_2pics_Plus",
		0x4032D:    "Drive_Continuous_Bracket_20Ev_2pics_Minus",
		0x4032E:    "Drive_Continuous_Bracket_20Ev_7pics",
		0x4032F:    "Drive_Continuous_Bracket_23Ev_2pics_Plus",
		0x40330:    "Drive_Continuous_Bracket_23Ev_2pics_Minus",
		0x40331:    "Drive_Continuous_Bracket_23Ev_3pics",
		0x40332:    "Drive_Continuous_Bracket_23Ev_5pics",
		0x40333:    "Drive_Continuous_Bracket_25Ev_2pics_Plus",
		0x40334:    "Drive_Continuous_Bracket_25Ev_2pics_Minus",
		0x40335:    "Drive_Continuous_Bracket_25Ev_3pics",
		0x40336:    "Drive_Continuous_Bracket_25Ev_5pics",
		0x40337:    "Drive_Continuous_Bracket_27Ev_2pics_Plus",
		0x40338:    "Drive_Continuous_Bracket_27Ev_2pics_Minus",
		0x40339:    "Drive_Continuous_Bracket_27Ev_3pics",
		0x4033A:    "Drive_Continuous_Bracket_27Ev_5pics",
		0x4033B:    "Drive_Continuous_Bracket_30Ev_2pics_Plus",
		0x4033C:    "Drive_Continuous_Bracket_30Ev_2pics_Minus",
		0x50001:    "Drive_Single_Bracket_03Ev_3pics",
		0x50002:    "Drive_Single_Bracket_03Ev_5pics",
		0x50003:    "Drive_Single_Bracket_03Ev_9pics",
		0x50004:    "Drive_Single_Bracket_05Ev_3pics",
		0x50005:    "Drive_Single_Bracket_05Ev_5pics",
		0x50006:    "Drive_Single_Bracket_05Ev_9pics",
		0x50007:    "Drive_Single_Bracket_07Ev_3pics",
		0x50008:    "Drive_Single_Bracket_07Ev_5pics",
		0x50009:    "Drive_Single_Bracket_07Ev_9pics",
		0x5000A:    "Drive_Single_Bracket_10Ev_3pics",
		0x5000B:    "Drive_Single_Bracket_10Ev_5pics",
		0x5000C:    "Drive_Single_Bracket_10Ev_9pics",
		0x5000D:    "Drive_Single_Bracket_20Ev_3pics",
		0x5000E:    "Drive_Single_Bracket_20Ev_5pics",
		0x5000F:    "Drive_Single_Bracket_30Ev_3pics",
		0x50010:    "Drive_Single_Bracket_30Ev_5pics",
		0x50011:    "Drive_Single_Bracket_03Ev_2pics_Plus",
		0x50012:    "Drive_Single_Bracket_03Ev_2pics_Minus",
		0x50013:    "Drive_Single_Bracket_03Ev_7pics",
		0x50014:    "Drive_Single_Bracket_05Ev_2pics_Plus",
		0x50015:    "Drive_Single_Bracket_05Ev_2pics_Minus",
		0x50016:    "Drive_Single_Bracket_05Ev_7pics",
		0x50017:    "Drive_Single_Bracket_07Ev_2pics_Plus",
		0x50018:    "Drive_Single_Bracket_07Ev_2pics_Minus",
		0x50019:    "Drive_Single_Bracket_07Ev_7pics",
		0x5001A:    "Drive_Single_Bracket_10Ev_2pics_Plus",
		0x5001B:    "Drive_Single_Bracket_10Ev_2pics_Minus",
		0x5001C:    "Drive_Single_Bracket_10Ev_7pics",
		0x5001D:    "Drive_Single_Bracket_13Ev_2pics_Plus",
		0x5001E:    "Drive_Single_Bracket_13Ev_2pics_Minus",
		0x5001F:    "Drive_Single_Bracket_13Ev_3pics",
		0x50020:    "Drive_Single_Bracket_13Ev_5pics",
		0x50021:    "Drive_Single_Bracket_13Ev_7pics",
		0x50022:    "Drive_Single_Bracket_15Ev_2pics_Plus",
		0x50023:    "Drive_Single_Bracket_15Ev_2pics_Minus",
		0x50024:    "Drive_Single_Bracket_15Ev_3pics",
		0x50025:    "Drive_Single_Bracket_15Ev_5pics",
		0x50026:    "Drive_Single_Bracket_15Ev_7pics",
		0x50027:    "Drive_Single_Bracket_17Ev_2pics_Plus",
		0x50028:    "Drive_Single_Bracket_17Ev_2pics_Minus",
		0x50029:    "Drive_Single_Bracket_17Ev_3pics",
		0x5002A:    "Drive_Single_Bracket_17Ev_5pics",
		0x5002B:    "Drive_Single_Bracket_17Ev_7pics",
		0x5002C:    "Drive_Single_Bracket_20Ev_2pics_Plus",
		0x5002D:    "Drive_Single_Bracket_20Ev_2pics_Minus",
		0x5002E:    "Drive_Single_Bracket_20Ev_7pics",
		0x5002F:    "Drive_Single_Bracket_23Ev_2pics_Plus",
		0x50030:    "Drive_Single_Bracket_23Ev_2pics_Minus",
		0x50031:    "Drive_Single_Bracket_23Ev_3pics",
		0x50032:    "Drive_Single_Bracket_23Ev_5pics",
		0x50033:    "Drive_Single_Bracket_25Ev_2pics_Plus",
		0x50034:    "Drive_Single_Bracket_25Ev_2pics_Minus",
		0x50035:    "Drive_Single_Bracket_25Ev_3pics",
		0x50036:    "Drive_Single_Bracket_25Ev_5pics",
		0x50037:    "Drive_Single_Bracket_27Ev_2pics_Plus",
		0x50038:    "Drive_Single_Bracket_27Ev_2pics_Minus",
		0x50039:    "Drive_Single_Bracket_27Ev_3pics",
		0x5003A:    "Drive_Single_Bracket_27Ev_5pics",
		0x5003B:    "Drive_Single_Bracket_30Ev_2pics_Plus",
		0x5003C:    "Drive_Single_Bracket_30Ev_2pics_Minus",
		0x60001:    "Drive_WB_Bracket_Lo",
		0x60002:    "Drive_WB_Bracket_Hi",
		0x70001:    "Drive_DRO_Bracket_Lo",
		0x70002:    "Drive_DRO_Bracket_Hi",
		0x80001:    "Drive_Continuous_Timer_3pics",
		0x80002:    "Drive_Continuous_Timer_5pics",
		0x80003:    "Drive_Continuous_Timer_2s_3pics",
		0x80004:    "Drive_Continuous_Timer_2s_5pics",
		0x80005:    "Drive_Continuous_Timer_5s_3pics",
		0x80006:    "Drive_Continuous_Timer_5s_5pics",
		0x10000001: "Drive_LPF_Bracket",
		0x10000002: "Drive_RemoteCommander",
		0x10000003: "Drive_MirrorUp",
		0x10000004: "Drive_SelfPortrait_1",
		0x10000005: "Drive_SelfPortrait_2",
	},
	"CrDualGain": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEframingAreaGroup": {
		0x1: "EframingInputArea",
		0x2: "EframingOutputArea",
	},
	"CrEframingAreaNumber": {
		0x1: "EframingArea1",
		0x2: "EframingArea2",
		0x3: "EframingArea3",
		0x4: "EframingArea4",
	},
	"CrEframingAutoFraming": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEframingHDMICrop": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEframingModeAuto": {
		0x1: "Auto",
		0x2: "TouchKick",
		0x3: "TimeSequenceA",
		0x4: "TimeSequenceB",
	},
	"CrEframingProductionEffect": {
		0x1: "Off",
		0x2: "IntervalZoomInOut_15sec",
		0x3: "IntervalZoomInOut_30sec",
	},
	"CrEframingRecordingImageCrop": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEframingScaleAuto": {
		0x1: "Low",
		0x2: "Mid",
		0x3: "High",
	},
	"CrEframingTrackingStartMode": {
		0x1: "Auto",
		0x2: "Manual",
	},
	"CrEframingType": {
		0x1: "None",
		0x2: "Auto",
		0x3: "Single",
		0x5: "PTZ",
		0x8: "HoldCurrentPosition",
		0x9: "ForceZoomOut",
	},
	"CrElectricFrontCurtainShutter": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEmbedLUTFile": {
		0x1: "Off",
		0x2: "On",
	},
	"CrEnlargeScreenSetting": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrExposureCtrlType": {
		0x1: "PASMMode",
		0x2: "FlexibleExposureMode",
	},
	"CrExposureProgram": {
		0x1:    "Exposure_M_Manual",
		0x2:    "Exposure_P_Auto",
		0x3:    "Exposure_A_AperturePriority",
		0x4:    "Exposure_S_ShutterSpeedPriority",
		0x5:    "Exposure_Program_Creative",
		0x6:    "Exposure_Program_Action",
		0x7:    "Exposure_Portrait",
		0x8000: "Exposure_Auto",
		0x8001: "Exposure_Auto_Plus",
		0x8002: "Exposure_P_A",
		0x8003: "Exposure_P_S",
		0x8004: "Exposure_Sports_Action",
		0x8005: "Exposure_Sunset",
		0x8006: "Exposure_Night",
		0x8007: "Exposure_Landscape",
		0x8008: "Exposure_Macro",
		0x8009: "Exposure_HandheldTwilight",
		0x800A: "Exposure_NightPortrait",
		0x800B: "Exposure_AntiMotionBlur",
		0x800C: "Exposure_Pet",
		0x800D: "Exposure_Gourmet",
		0x800E: "Exposure_Fireworks",
		0x800F: "Exposure_HighSensitivity",
		0x8020: "Exposure_MemoryRecall",
		0x8031: "Exposure_ContinuousPriority_AE_8pics",
		0x8032: "Exposure_ContinuousPriority_AE_10pics",
		0x8033: "Exposure_ContinuousPriority_AE_12pics",
		0x8040: "Exposure_3D_SweepPanorama",
		0x8041: "Exposure_SweepPanorama",
		0x8050: "Exposure_Movie_P",
		0x8051: "Exposure_Movie_A",
		0x8052: "Exposure_Movie_S",
		0x8053: "Exposure_Movie_M",
		0x8054: "Exposure_Movie_Auto",
		0x8055: "Exposure_Movie_F",
		0x8059: "Exposure_Movie_SQMotion_P",
		0x805A: "Exposure_Movie_SQMotion_A",
		0x805B: "Exposure_Movie_SQMotion_S",
		0x805C: "Exposure_Movie_SQMotion_M",
		0x805D: "Exposure_Movie_SQMotion_AUTO",
		0x805E: "Exposure_Movie_SQMotion_F",
		0x8060: "Exposure_Flash_Off",
		0x8070: "Exposure_PictureEffect",
		0x8080: "Exposure_HiFrameRate_P",
		0x8081: "Exposure_HiFrameRate_A",
		0x8082: "Exposure_HiFrameRate_S",
		0x8083: "Exposure_HiFrameRate_M",
		0x8084: "Exposure_SQMotion_P",
		0x8085: "Exposure_SQMotion_A",
		0x8086: "Exposure_SQMotion_S",
		0x8087: "Exposure_SQMotion_M",
		0x8088: "Exposure_MOVIE",
		0x8089: "Exposure_STILL",
		0x8092: "Exposure_Movie_IntervalRec_F",
		0x8093: "Exposure_Movie_IntervalRec_P",
		0x8094: "Exposure_Movie_IntervalRec_A",
		0x8095: "Exposure_Movie_IntervalRec_S",
		0x8096: "Exposure_Movie_IntervalRec_M",
		0x8097: "Exposure_Movie_IntervalRec_AUTO",
	},
	"CrExposureStep": {
		0x0: "Invalid",
	},
	"CrExtendedInterfaceMode": {
		0x1: "Off",
		0x2: "On",
	},
	"CrExtendedShutterSpeed": {
		0x0:                "Bulb",
		0xFFFFFFFFFFFFFFFF: "Nothing",
	},
	"CrFTPAutoTransfer": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFTPAutoTransferTarget": {
		0x1: "StillOnly",
		0x2: "MovieOnly",
		0x3: "StillAndMovie",
	},
	"CrFTPAutoTransferTargetMovie": {
		0x1: "All",
		0x2: "OnlyShotMark",
		0x3: "ProtectOnly",
	},
	"CrFTPAutoTransferTargetStill": {
		0x1: "All",
		0x2: "ProtectOnly",
	},
	"CrFTPConnectionErrorInfo": {
		0xFFFF: "Unknown",
		0x0:    "NoError",
		0x1:    "CameraSystemError",
		0x2:    "WiFi_HardwareError",
		0x3:    "WiredLAN_HardwareError",
		0x4:    "AP_NotReg",
		0x5:    "AP_NotFound",
		0x6:    "AP_ConnectionError",
		0x7:    "AP_PasswordError",
		0x8:    "InvalidKeyError_WEP_StaticIPAddrSettingError",
		0x9:    "InvalidKeyError_WEP_IPAddrAcquisitionError",
		0xA:    "DHCP_IPAddrAcquisitionError",
		0xB:    "DNS_IPAddrAcquisitionError",
		0xC:    "AirplaneModeON",
		0xD:    "LANCableError",
		0xE:    "FTPServerSettingNotSet",
		0xF:    "FTPServerSettingError",
		0x10:   "FTPServerSevered",
		0x11:   "CertificateError",
		0x12:   "DirectoryCreateError",
		0x13:   "AuthorityError_FTPServerOverCapacity",
		0x14:   "CantRecognizeUSBAdapter",
		0x15:   "CantRecognizeUSBDevice",
		0x16:   "CheckConnectDevice",
		0x17:   "Reconnecting_FailedConnectServer",
		0x18:   "Reconnecting_CantTransfer",
	},
	"CrFTPConnectionStatus": {
		0x1: "Connecting",
		0x2: "Connected",
		0x3: "Connected_ServerError",
		0x4: "ConnectionError",
	},
	"CrFTPFunction": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFTPJobCompleteAction": {
		0x0: "Invalid",
		0x1: "NoAction",
		0x2: "DeleteFile",
	},
	"CrFTPJobControlType": {
		0x1: "Add",
		0x2: "Delete",
		0x3: "Suspend",
		0x4: "Resume",
	},
	"CrFTPJobDeleteAction": {
		0x0: "Invalid",
		0x1: "NoAction",
		0x2: "DeleteFile",
	},
	"CrFTPJobDeleteType": {
		0x0: "Individual",
		0x1: "All",
		0x2: "FinishedAll",
	},
	"CrFTPJobSlotId": {
		0x0: "Invalid",
		0x1: "Slot1",
		0x2: "Slot2",
		0x3: "Slot3",
	},
	"CrFTPJobStatus": {
		0x0:     "Invalid",
		0x100:   "Waiting",
		0x200:   "Transferring",
		0x400:   "Completed",
		0x800:   "Aborted",
		0x10000: "OtherErr",
		0x10001: "DestAuthFailed",
		0x10002: "ServerCapacityOver",
		0x10003: "FileAccessErr",
		0x10004: "DestCertErr",
		0x10005: "MediaAccessErr",
		0x10006: "DestConnErr",
		0x10007: "DestServerErr",
		0x10008: "UploadErr",
		0x10009: "DestCertNotValid",
		0x1000A: "DestCertExpired",
		0x1000B: "PASVNotSupport",
		0x1000C: "ChunkTransErr",
	},
	"CrFTPJobTrimType": {
		0x0: "NoTrim",
		0x1: "Trim",
	},
	"CrFTPPowerSave": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFTPServerDirectoryHierarchyType": {
		0x0: "Invalid",
		0x1: "Standard",
		0x2: "SameAsInCamera",
	},
	"CrFTPServerPassiveMode": {
		0x0: "Invalid",
		0x1: "Off",
		0x2: "On",
	},
	"CrFTPServerPasswordExists": {
		0x0: "FTPServerPassword_NotUse",
		0x1: "FTPServerPassword_Use",
	},
	"CrFTPServerRootCertificateErrorSetting": {
		0x0: "Invalid",
		0x1: "Connect",
		0x2: "NotConnect",
	},
	"CrFTPServerSameNameFileOverwriteType": {
		0x0: "Invalid",
		0x1: "Overwrite",
		0x2: "NotOverwrite",
	},
	"CrFTPServerServiceType": {
		0x0: "Invalid",
		0x1: "FTP",
	},
	"CrFTPServerSettingOperationEnableStatus": {
		0x0: "FTPServerSettingOperation_Disable",
		0x1: "FTPServerSettingOperation_Enable",
	},
	"CrFTPServerUsingSecureProtocol": {
		0x0: "Invalid",
		0x1: "Off",
		0x2: "On",
		0x3: "On_SFTP",
	},
	"CrFTPTransferSettingReadOperationEnableStatus": {
		0x0: "FTPTransferSettingReadOperation_Disable",
		0x1: "FTPTransferSettingReadOperation_Enable",
	},
	"CrFTPTransferSettingSaveOperationEnableStatus": {
		0x0: "FTPTransferSettingSaveOperation_Disable",
		0x1: "FTPTransferSettingSaveOperation_Enable",
	},
	"CrFTPTransferSettingSaveReadState": {
		0x0: "Idle",
		0x1: "Reading",
	},
	"CrFTPTransferStillImageQualitySize": {
		0x1: "Small",
		0x2: "Large",
	},
	"CrFTPTransferTargetMovie": {
		0x1: "ProxyOnly",
		0x2: "OriginalOnly",
		0x3: "OriginalAndProxy",
	},
	"CrFTPTransferTargetStill": {
		0x1: "JpegHeifOnly",
		0x2: "RawOnly",
		0x3: "RawAndJpegHeif",
	},
	"CrFaceEyeDetectionAF": {
		0x1: "Off",
		0x2: "FaceEyeOnlyAF",
		0x3: "FaceEyePriorityAF",
	},
	"CrFaceEyeDetectionAFStatus": {
		0x1: "FaceEyeOnlyAFStop",
		0x2: "FaceEyeOnlyAF",
		0x3: "FaceEyePriorityAF",
	},
	"CrFaceEyeFrameDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFaceFrameType": {
		0x0: "Unknown",
		0x1: "DetectedFace",
		0x2: "AF_TargetFace",
		0x3: "PersonalRecognitionFace",
		0x4: "SmileDetectionFace",
		0x5: "SelectedFace",
		0x6: "AF_TargetSelectionFace",
		0x7: "SmileDetectionSelectFace",
	},
	"CrFacePriorityInMultiMetering": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFileFormatMovie": {
		0x0:  "AVCHD",
		0x1:  "MP4",
		0x2:  "XAVC_S_4K",
		0x3:  "XAVC_S_HD",
		0x4:  "XAVC_HS_8K",
		0x5:  "XAVC_HS_4K",
		0x6:  "XAVC_S_L_4K",
		0x7:  "XAVC_S_L_HD",
		0x8:  "XAVC_S_I_4K",
		0x9:  "XAVC_S_I_HD",
		0xA:  "XAVC_I",
		0xB:  "XAVC_L",
		0xC:  "XAVC_HS_HD",
		0xD:  "XAVC_S_I_DCI_4K",
		0xE:  "XAVC_H_I_HQ",
		0xF:  "XAVC_H_I_SQ",
		0x10: "XAVC_H_L",
		0x11: "X_OCN_XT",
		0x12: "X_OCN_ST",
		0x13: "X_OCN_LT",
		0x14: "XAVC_Proxy",
		0x15: "XAVC_HS_L_422",
		0x16: "XAVC_HS_L_420",
		0x17: "XAVC_S_L_422",
		0x18: "XAVC_S_L_420",
		0x19: "XAVC_S_I_422",
		0x1A: "MPEG_HD_422",
	},
	"CrFileSettingsCameraId": {
		0x1:  "A",
		0x2:  "B",
		0x3:  "C",
		0x4:  "D",
		0x5:  "E",
		0x6:  "F",
		0x7:  "G",
		0x8:  "H",
		0x9:  "I",
		0xA:  "J",
		0xB:  "K",
		0xC:  "L",
		0xD:  "M",
		0xE:  "N",
		0xF:  "O",
		0x10: "P",
		0x11: "Q",
		0x12: "R",
		0x13: "S",
		0x14: "T",
		0x15: "U",
		0x16: "V",
		0x17: "W",
		0x18: "X",
		0x19: "Y",
		0x1A: "Z",
	},
	"CrFileSettingsCameraPosition": {
		0x1: "Center",
		0x2: "Left",
		0x3: "Right",
	},
	"CrFileType": {
		0x0: "None",
		0x1: "Jpeg",
		0x2: "Raw",
		0x3: "RawJpeg",
		0x4: "RawHeif",
		0x5: "Heif",
	},
	"CrFlashMode": {
		0x1: "Flash_Auto",
		0x2: "Flash_Off",
		0x3: "Flash_Fill",
		0x4: "Flash_ExternalSync",
		0x5: "Flash_SlowSync",
		0x6: "Flash_RearSync",
	},
	"CrFlickerLessShooting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFlickerLessShootingStatus": {
		0x0: "NotDetected",
		0x1: "Detected",
	},
	"CrFlickerScanEnableStatus": {
		0x0: "FlickerScan_Disable",
		0x1: "FlickerScan_Enable",
	},
	"CrFlickerScanStatus": {
		0x0: "Invalid",
		0x1: "Idle",
		0x2: "FlickerScanning",
	},
	"CrFnumberSet": {
		0xFFFD: "Fnumber_IrisClose",
		0xFFFE: "Fnumber_Unknown",
		0xFFFF: "Fnumber_Nothing",
	},
	"CrFocalDistanceUnitSetting": {
		0x1: "Meter",
		0x2: "Feet",
	},
	"CrFocusArea": {
		0x0:  "Unknown",
		0x1:  "Wide",
		0x2:  "Zone",
		0x3:  "Center",
		0x4:  "Flexible_Spot_S",
		0x5:  "Flexible_Spot_M",
		0x6:  "Flexible_Spot_L",
		0x7:  "Expand_Flexible_Spot",
		0x8:  "Flexible_Spot",
		0x11: "Tracking_Wide",
		0x12: "Tracking_Zone",
		0x13: "Tracking_Center",
		0x14: "Tracking_Flexible_Spot_S",
		0x15: "Tracking_Flexible_Spot_M",
		0x16: "Tracking_Flexible_Spot_L",
		0x17: "Tracking_Expand_Flexible_Spot",
		0x18: "Tracking_Flexible_Spot",
		0x19: "Flexible_Spot_XS",
		0x1A: "Flexible_Spot_XL",
		0x1B: "Flexible_Spot_FreeSize1",
		0x1C: "Flexible_Spot_FreeSize2",
		0x1D: "Flexible_Spot_FreeSize3",
		0x23: "Tracking_Flexible_Spot_XS",
		0x24: "Tracking_Flexible_Spot_XL",
		0x25: "Tracking_Flexible_Spot_FreeSize1",
		0x26: "Tracking_Flexible_Spot_FreeSize2",
		0x27: "Tracking_Flexible_Spot_FreeSize3",
	},
	"CrFocusBracketExposureLock1stImg": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFocusBracketIntervalUntilNextShot": {
		0x0:    "Invalid",
		0xFFFF: "ShortestInterval",
	},
	"CrFocusBracketOrder": {
		0x1: "0ToMinusToPlus",
		0x2: "0ToPlus",
	},
	"CrFocusBracketRecordingFolder": {
		0x1: "CurrentFolder",
		0x2: "NewFolder",
	},
	"CrFocusBracketShootingStatus": {
		0x0: "FocusBracket_NotShooting",
		0x1: "FocusBracket_Shooting",
	},
	"CrFocusDrivingStatus": {
		0x1: "NotDriving",
		0x2: "Driving",
	},
	"CrFocusFrameSelectState": {
		0x0: "Unknown",
	},
	"CrFocusFrameState": {
		0x0: "Unknown",
		0x1: "NotFocused",
		0x2: "Focused",
		0x3: "FocusFrameSelection",
		0x4: "Moving",
		0x6: "RegistrationAF",
		0x7: "Island",
	},
	"CrFocusFrameType": {
		0x0: "Unknown",
		0x1: "PhaseDetection_AFSensor",
		0x2: "PhaseDetection_ImageSensor",
		0x3: "Wide",
		0x4: "Zone",
		0x5: "CentralEmphasis",
		0x6: "ContrastFlexibleMain",
		0x7: "ContrastFlexibleAssist",
		0x8: "Contrast",
		0xF: "FrameSomewhere",
	},
	"CrFocusIndicator": {
		0x1:    "Unlocked",
		0x102:  "Focused_AF_S",
		0x202:  "NotFocused_AF_S",
		0x103:  "Focused_AF_C",
		0x203:  "NotFocused_AF_C",
		0x303:  "TrackingSubject_AF_C",
		0x1008: "Unpause",
		0x2008: "Pause",
	},
	"CrFocusMagnificationTime": {
		0xFF: "NoLimit",
	},
	"CrFocusMap": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFocusMode": {
		0x1: "Focus_MF",
		0x2: "Focus_AF_S",
		0x3: "Focus_AF_C",
		0x4: "Focus_AF_A",
		0x5: "Focus_AF_D",
		0x6: "Focus_DMF",
		0x7: "Focus_PF",
	},
	"CrFocusModeSetting": {
		0x1: "Automatic",
		0x2: "Manual",
	},
	"CrFocusModeStatus": {
		0x1: "FocusHold",
		0x2: "MF_Operation",
		0x3: "AF_Operation",
	},
	"CrFocusOperation": {
		0xFFFFFFFFFFFFFFFF: "Wide",
		0x0:                "Stop",
		0x1:                "Tele",
	},
	"CrFocusOperationWithInt16EnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrFocusTouchSpotStatus": {
		0x1: "Stopped",
		0x2: "Running",
	},
	"CrFocusTrackingStatus": {
		0x1: "OFF",
		0x2: "Focusing",
		0x3: "Tracking",
	},
	"CrForcedFileNumberReset": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrFrameInfoType": {
		0x0: "Unknown",
		0x1: "FocusFrameInfo",
		0x2: "Magnifier_Position",
		0x4: "FaceFrameInfo",
		0x5: "TrackingFrameInfo",
		0x6: "FramingFrameInfo",
		0x7: "Level",
	},
	"CrFramingFrameType": {
		0x0: "Unknown",
		0x1: "Auto",
	},
	"CrFullTimeDMF": {
		0x1: "Off",
		0x2: "On",
	},
	"CrFunctionOfRemoteTouchOperation": {
		0x1: "Tracking_AF",
		0x2: "Spot_AF",
		0x3: "AFAreaSelect",
	},
	"CrFunctionOfTouchOperation": {
		0x1: "Off",
		0x2: "Shutter",
		0x3: "Focus",
		0x4: "Tracking",
		0x5: "AE",
		0x6: "ShutterAndAEOn",
		0x7: "ShutterAndAEOff",
		0x8: "FocusAndAEOn",
		0x9: "FocusAndAEOff",
		0xA: "TrackingAndAEOn",
		0xB: "TrackingAndAEOff",
	},
	"CrGainBaseIsoSensitivity": {
		0x1: "High",
		0x2: "Low",
	},
	"CrGainBaseSensitivity": {
		0x1: "High",
		0x2: "Low",
	},
	"CrGainControlSetting": {
		0x1: "GainControl_Automatic",
		0x2: "GainControl_Manual",
	},
	"CrGainUnitSetting": {
		0x1: "dB",
		0x2: "ISO",
	},
	"CrGammaDisplayAssist": {
		0x1: "Off",
		0x2: "On",
	},
	"CrGammaDisplayAssistType": {
		0x1:   "Auto",
		0x302: "SLog2_709_800",
		0x303: "SLog3_709_800",
		0x401: "HLG_BT2020",
		0x402: "HLG_709",
	},
	"CrGetContentsCompressedDataType": {
		0x0: "Invalid",
		0x1: "Thumbnail",
		0x2: "Screennail",
	},
	"CrGetContentsDataControlType": {
		0x0: "Resume",
		0x1: "Pause",
		0x2: "Cancel",
	},
	"CrGetContentsInfoListType": {
		0x0: "All",
		0x1: "Range_Month",
		0x2: "Range_Day",
		0x3: "Range_Hour",
		0x4: "Count",
	},
	"CrGridLineDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrGridLineType": {
		0x1:  "RuleOf3rdsGrid",
		0x2:  "SquareGrid",
		0x3:  "DiagAndSquareGrid",
		0x4:  "GoldenRatioGrid",
		0x11: "Custom1",
		0x12: "Custom2",
		0x13: "Custom3",
		0x14: "Custom4",
	},
	"CrGuideframeDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHDMIOutput4KSettingMovie": {
		0x1:   "59_94p_10bit",
		0x2:   "50_00p_10bit",
		0x3:   "29_97p_10bit",
		0x4:   "25_00p_10bit",
		0x5:   "24_00p_10bit",
		0x6:   "23_98p_10bit",
		0x101: "59_94p_8bit",
		0x102: "50_00p_8bit",
		0x103: "29_97p_8bit",
		0x104: "25_00p_8bit",
		0x106: "23_98p_8bit",
	},
	"CrHDMIOutputAudioCH": {
		0x3: "CH1CH2",
		0xC: "CH3CH4",
	},
	"CrHDMIOutputColorGamutForRAWOutMovie": {
		0x1: "S_Gamut3_Cine_SLog3",
		0x2: "S_Gamut3_SLog3",
	},
	"CrHDMIOutputRAWMovie": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHDMIOutputRawSettingMovie": {
		0x1: "59_94p",
		0x2: "50_00p",
		0x3: "29_97p",
		0x4: "25_00p",
		0x5: "24_00p",
		0x6: "23_98p",
	},
	"CrHDMIOutputRecControlMovie": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHDMIOutputRecMediaMovie": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHDMIOutputTimeCodeMovie": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHDMIResolution": {
		0x1:    "4320p_2160p",
		0x2:    "2160p",
		0x3:    "2160p_1080p",
		0x4:    "1080p",
		0x5:    "720p",
		0x6:    "480p",
		0x7:    "576p",
		0x104:  "1080i",
		0x106:  "480i",
		0x107:  "576i",
		0xFFFF: "Auto",
	},
	"CrHLGStillImage": {
		0x1: "Off",
		0x2: "On",
	},
	"CrHighIsoNR": {
		0x1: "Off",
		0x2: "Low",
		0x3: "Normal",
		0x4: "High",
	},
	"CrHighResolutionShutterSpeed": {
		0xFFFFFFFFFFFFFFFF: "Nothing",
	},
	"CrHighResolutionShutterSpeedSetting": {
		0x0: "Off",
		0x1: "On",
	},
	"CrHomeMenuSetting": {
		0x1: "NDFilter",
		0x2: "Aperture",
	},
	"CrIPSetupProtocolSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrIRRemoteSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrISOMode": {
		0x0:      "ISO_Normal",
		0x1:      "ISO_MultiFrameNR",
		0x2:      "ISO_MultiFrameNR_High",
		0x10:     "ISO_Ext",
		0xFFFFFF: "ISO_AUTO",
	},
	"CrImageIDNumSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrImageQuality": {
		0x0: "Unknown",
		0x1: "Light",
		0x2: "Standard",
		0x3: "Fine",
		0x4: "ExFine",
	},
	"CrImageSize": {
		0x1: "L",
		0x2: "M",
		0x3: "S",
		0x4: "VGA",
	},
	"CrImageStabilizationFramingStabilizer": {
		0x1: "OFF",
		0x2: "ON_Manual",
		0x3: "ON_Center",
	},
	"CrImageStabilizationLevelMovie": {
		0x1: "OFF",
		0x2: "Low",
		0x3: "High",
	},
	"CrImageStabilizationSteadyShot": {
		0x1: "Off",
		0x2: "On",
	},
	"CrImageStabilizationSteadyShotAdjust": {
		0x1: "Automatic",
		0x2: "Manual",
	},
	"CrImageStabilizationSteadyShotMovie": {
		0x1: "Off",
		0x2: "Standard",
		0x3: "Active",
		0x4: "DynamicActive",
	},
	"CrImagerMode_ImagerAspectRatio": {
		0x1: "3_2",
		0x2: "4_3",
		0x3: "6_5",
		0x4: "16_9",
		0x5: "17_9",
	},
	"CrImagerMode_ImagerImageSize": {
		0x1: "FullFrame",
		0x2: "FullFrameCrop",
		0x3: "Super35",
		0x4: "Super35Crop",
	},
	"CrImagerScanMode": {
		0x1: "Auto",
		0x2: "FullFrame",
		0x3: "S35",
	},
	"CrIntervalRecAETrackingSensitivity": {
		0x1: "Off",
		0x2: "Low",
		0x3: "Mid",
		0x4: "High",
	},
	"CrIntervalRecMode": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrIntervalRecShootIntervalPriority": {
		0x1: "Off",
		0x2: "On",
	},
	"CrIntervalRecShutterType": {
		0x1: "Auto",
		0x2: "MechanicalShutter",
		0x3: "ElectronicShutter",
	},
	"CrIntervalRecStatus": {
		0x1: "WaitingStart",
		0x2: "IntervalShooting",
	},
	"CrIntervalRecTimeMovie": {
		0x1:     "1sec",
		0x2:     "2sec",
		0x3:     "3sec",
		0x4:     "4sec",
		0x5:     "5sec",
		0x6:     "6sec",
		0x7:     "7sec",
		0x8:     "8sec",
		0x9:     "9sec",
		0xA:     "10sec",
		0xF:     "15sec",
		0x14:    "20sec",
		0x1E:    "30sec",
		0x28:    "40sec",
		0x32:    "50sec",
		0x3C:    "1min",
		0x78:    "2min",
		0xB4:    "3min",
		0xF0:    "4min",
		0x12C:   "5min",
		0x168:   "6min",
		0x1A4:   "7min",
		0x1E0:   "8min",
		0x21C:   "9min",
		0x258:   "10min",
		0x384:   "15min",
		0x4B0:   "20min",
		0x708:   "30min",
		0x960:   "40min",
		0xBB8:   "50min",
		0xE10:   "1hour",
		0x1C20:  "2hour",
		0x2A30:  "3hour",
		0x3840:  "4hour",
		0x5460:  "6hour",
		0xA8C0:  "12hour",
		0x15180: "24hour",
	},
	"CrIrisCloseSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrIrisDisplayUnit": {
		0x1: "Auto",
		0x2: "FLock",
		0x3: "TLock",
	},
	"CrIrisModeSetting": {
		0x1: "IrisMode_Automatic",
		0x2: "IrisMode_Manual",
	},
	"CrIsoAutoMinShutterSpeedManual": {
		0x0: "Invalid",
	},
	"CrIsoAutoMinShutterSpeedMode": {
		0x1: "Preset",
		0x2: "Manual",
	},
	"CrIsoAutoMinShutterSpeedPreset": {
		0x1: "Slower",
		0x2: "Slow",
		0x3: "Standard",
		0x4: "Fast",
		0x5: "Faster",
	},
	"CrJpegQuality": {
		0x0: "Unknown",
		0x1: "Light",
		0x2: "Standard",
		0x3: "Fine",
		0x4: "ExFine",
	},
	"CrLanguageSetting": {
		0x0:  "Invalid",
		0x1:  "English",
		0x2:  "Japanese",
		0x3:  "SimplifiedChinese",
		0x4:  "TraditionalChinese",
		0x5:  "Korean",
		0x6:  "Spanish",
		0x7:  "Russian",
		0x8:  "BrazilianPortuguese",
		0x9:  "Portuguese",
		0xA:  "Indonesian",
		0xB:  "French",
		0xC:  "German",
		0xD:  "Italian",
		0xE:  "Dutch",
		0xF:  "Greek",
		0x10: "Arabic",
		0x11: "Persian",
		0x12: "Thai",
		0x13: "Turkish",
		0x14: "Polish",
		0x15: "Czech",
		0x16: "Hungarian",
		0x17: "Malay",
		0x18: "Hindi",
	},
	"CrLensCompensationBreathing": {
		0x1: "Off",
		0x2: "On",
	},
	"CrLensCompensationChromaticAberration": {
		0x1: "Off",
		0x2: "Auto",
	},
	"CrLensCompensationDistortion": {
		0x1: "Off",
		0x2: "Auto",
	},
	"CrLensCompensationShading": {
		0x1: "Off",
		0x2: "Auto",
		0x3: "Low",
	},
	"CrLensInformationEnableStatus": {
		0x0: "LensInformation_Disable",
		0x1: "LensInformation_Enable",
	},
	"CrLensInformationType": {
		0x0: "Undefined",
		0x1: "Feet",
		0x2: "Meter",
	},
	"CrLevelState": {
		0x1: "Level_Off",
		0x2: "Level_On",
	},
	"CrLiveViewDisplayEffect": {
		0x0: "Unknown",
		0x1: "ON",
		0x2: "OFF",
	},
	"CrLiveViewPropertyCode": {
		0x122:  "LiveViewProperty_Focus_Magnifier_Position",
		0x581:  "LiveViewProperty_FaceFrame",
		0x582:  "LiveViewProperty_Level",
		0x2000: "LiveViewProperty__LiveViewMaxVal",
	},
	"CrLiveViewProtocol": {
		0x0: "None",
		0x1: "Main",
		0x2: "Alt",
	},
	"CrLiveViewStatus": {
		0x0: "LiveView_NotSupport",
		0x1: "LiveView_Disable",
		0x2: "LiveView_Enable",
	},
	"CrLockIndicator": {
		0x0: "Unknown",
		0x1: "Unlocked",
		0x2: "Locked",
	},
	"CrLogShootingMode": {
		0x1:   "Off",
		0x501: "FlexibleISO",
	},
	"CrLogShootingModeColorGamut": {
		0x1: "S_Gamut3_Cine",
		0x2: "S_Gamut3",
	},
	"CrLongExposureNR": {
		0x1: "Off",
		0x2: "On",
	},
	"CrMarkerDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrMediaFormat": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrMediaPlayer": {
		0x0: "None",
		0x1: "Player",
		0x2: "Recorder",
		0x3: "Player_Recorder",
	},
	"CrMediaSlotRecordingAvailableType": {
		0x0: "None",
		0x1: "Main",
		0x2: "Proxy",
		0x3: "MainAndProxy",
	},
	"CrMediaSlotWritingState": {
		0x1: "NotWriting",
		0x2: "ContentsWriting",
	},
	"CrMeteringMode": {
		0x1: "Metering_Average",
		0x2: "Metering_CenterWeightedAverage",
		0x3: "Metering_MultiSpot",
		0x4: "Metering_CenterSpot",
		0x5: "Metering_Multi",
		0x6: "Metering_CenterWeighted",
		0x7: "Metering_EntireScreenAverage",
		0x8: "Metering_Spot_Standard",
		0x9: "Metering_Spot_Large",
		0xA: "Metering_HighLightWeighted",
		0xB: "Metering_Standard",
		0xC: "Metering_Backlight",
		0xD: "Metering_Spotlight",
	},
	"CrMicrophoneDirectivity": {
		0x1: "Auto",
		0x2: "All",
		0x3: "Front",
		0x4: "Rear",
	},
	"CrMonitorBrightnessType": {
		0x1: "Manual",
		0x2: "SunnyWeather",
	},
	"CrMonitorLUTSetting": {
		0x1: "MonitorLUT_OFF",
		0x2: "MonitorLUT_ON",
	},
	"CrMonitorLUTSettingOutputDestAssign": {
		0xFF:    "NumberMask",
		0x100:   "All",
		0x200:   "Stream",
		0x400:   "Proxy",
		0x800:   "HDMI",
		0x1000:  "SDI",
		0x2000:  "VF",
		0x4000:  "LCD",
		0x8000:  "InternalRec",
		0x10000: "SDI2",
	},
	"CrMonitoringDeliveringStatus": {
		0x1:    "RTSP",
		0x2:    "VenderProtocol",
		0xFFFF: "None",
	},
	"CrMonitoringDeliveryType": {
		0x0: "None",
		0x1: "Jpeg",
	},
	"CrMonitoringFormat_DeliveryImageQualityLevel": {
		0x0: "Invalid",
		0x1: "Level1",
		0x2: "Level2",
		0x3: "Level3",
		0x4: "Level4",
		0x5: "Level5",
	},
	"CrMonitoringFormat_FrameRate": {
		0x1: "7_50fps",
		0x2: "23_98fps",
		0x3: "24_00fps",
		0x4: "25_00fps",
		0x5: "29_97fps",
		0x6: "30_00fps",
	},
	"CrMonitoringFormat_Resolution": {
		0x1: "480x270",
		0x2: "640x336",
		0x3: "640x360",
		0x4: "1024x544",
		0x5: "1024x576",
		0x6: "1280x720",
		0x7: "1920x1080",
		0x8: "640x480",
		0x9: "1024x768",
		0xA: "320x240",
		0xB: "320x216",
		0xC: "320x184",
		0xD: "320x168",
	},
	"CrMonitoringFormat_VideoCodec": {
		0x1: "Jpeg",
		0x2: "H264",
		0x3: "H265",
	},
	"CrMonitoringIsDelivering": {
		0x0: "False",
		0x1: "True",
	},
	"CrMonitoringOutputDisplayHDMI": {
		0x1: "Off",
		0x2: "On",
	},
	"CrMonitoringOutputDisplaySDI": {
		0x1: "Off",
		0x2: "On",
	},
	"CrMonitoringOutputDisplaySetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrMonitoringOutputFormat": {
		0x0: "None",
		0x1: "59_94_720x480P",
		0x2: "1920x1080i",
		0x3: "1920x1080i_PsF",
		0x4: "1920x1080P",
		0x5: "1920x1080P_LevelA",
		0x6: "1920x1080P_LevelB",
		0x7: "3840x2160P",
		0x8: "4096x2160P",
		0x9: "1280x720P",
	},
	"CrMonitoringTransportProtocol": {
		0x0: "Invalid",
		0x1: "UDP",
		0x2: "TCP",
	},
	"CrMovieAngleOfViewPriority": {
		0x1: "Movie_AngleOfViewPriority_OFF",
		0x2: "Movie_AngleOfViewPriority_ON",
	},
	"CrMoviePlayingSpeed": {
		0xFFFFFFFFFFFFFFFF: "Nothing",
	},
	"CrMoviePlayingState": {
		0x0: "NotPlaying",
		0x1: "Playing",
	},
	"CrMovieQualityFullAutoMode": {
		0x1: "Off_Manual",
		0x2: "On_Auto",
	},
	"CrMovieRecButtonToggleEnableStatus": {
		0x0: "MovieRecButtonToggle_Disable",
		0x1: "MovieRecButtonToggle_Enable",
	},
	"CrMovieRecReviewPlayingState": {
		0x0: "NotPlaying",
		0x1: "Playing",
	},
	"CrMovieRecordingSelfTimer": {
		0x0: "Off",
		0x1: "On",
	},
	"CrMovieRecordingSelfTimerContinuous": {
		0x0: "Off",
		0x1: "On",
	},
	"CrMovieRecordingSelfTimerCountTime": {
		0x0: "None",
	},
	"CrMovieRecordingSelfTimerStatus": {
		0x0: "Idle",
		0x1: "CountingDown",
	},
	"CrMovieShootingMode": {
		0x1:   "Off",
		0x301: "CineEI",
		0x302: "CineEIQuick",
		0x401: "Custom",
		0x501: "FlexibleISO",
	},
	"CrMovieShootingModeColorGamut": {
		0x1: "S_Gamut3_Cine",
		0x2: "S_Gamut3",
	},
	"CrMovieShootingModeTargetDisplay": {
		0x1: "BT709",
		0x2: "BT2020",
	},
	"CrMovieXButton": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrMovie_Recording_State": {
		0x0: "Not_Recording",
		0x1: "Recording",
		0x2: "Recording_Failed",
		0x3: "IntervalRec_Waiting_Record",
	},
	"CrNDFilter": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrNDFilterMode": {
		0x1: "Auto",
		0x2: "Preset",
		0x3: "PresetClear",
		0x4: "Variable",
		0x5: "VariableClear",
		0x6: "Step",
		0x7: "StepClear",
	},
	"CrNDFilterModeSetting": {
		0x1: "Automatic",
		0x2: "Manual",
	},
	"CrNDFilterOpticalDensityValue": {
		0xFFFF: "Nothing",
	},
	"CrNDFilterPresetSelect": {
		0x1: "Preset1",
		0x2: "Preset2",
		0x3: "Preset3",
	},
	"CrNDFilterPresetValue": {
		0xFFFFFFFFFFFFFFFF: "Nothing",
	},
	"CrNDFilterSwitchingSetting": {
		0x1: "Preset",
		0x2: "Variable",
		0x3: "Step",
	},
	"CrNDFilterUnitSetting": {
		0x1: "OpticalDensity",
		0x2: "Transmittance",
	},
	"CrNDFilterValue": {
		0xFFFFFFFFFFFFFFFF: "Nothing",
	},
	"CrNDPresetOrVariableSwitchingSetting": {
		0x1: "Preset",
		0x2: "Variable",
	},
	"CrNearFarEnableStatus": {
		0x0: "NearFar_Disable",
		0x1: "NearFar_Enable",
	},
	"CrNoiseCutFilter": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrNoiseCutFilterForExternalMic": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrOSDImageMode": {
		0x0: "Off",
		0x1: "On",
	},
	"CrPTZFControlType": {
		0x1: "Absolute",
		0x2: "Relative",
		0x3: "Direction",
		0x4: "HomePosition",
		0x5: "Reset",
		0x6: "Cancel",
		0x7: "Max",
	},
	"CrPaintLookAutoKnee": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPaintLookDetailSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPaintLookKneeSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPaintLookMatrixSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPaintLookMultiMatrixAreaIndication": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPaintLookMultiMatrixAxis": {
		0x100: "B",
		0x101: "B_Plus",
		0x180: "B_Minus",
		0x200: "MG",
		0x201: "MG_Plus",
		0x280: "MG_Minus",
		0x300: "R",
		0x301: "R_Plus",
		0x400: "YL",
		0x401: "YL_Plus",
		0x480: "YL_Minus",
		0x500: "G",
		0x501: "G_Plus",
		0x580: "G_Minus",
		0x600: "CY",
		0x601: "CY_Plus",
	},
	"CrPanLimitMode": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPanPositionStatus": {
		0x1: "Idle",
		0x2: "Moving",
		0x3: "Unknown",
		0x4: "Uninitialized",
	},
	"CrPanTiltAccelerationRampCurve": {
		0x0: "Invalid",
	},
	"CrPeakingColor": {
		0x1: "White",
		0x2: "Blue",
		0x3: "Yellow",
		0x4: "Red",
	},
	"CrPeakingDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPeakingLevel": {
		0x1: "Low",
		0x2: "Mid",
		0x3: "High",
	},
	"CrPictureCacheRecSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPictureCacheRecSizeAndTime_CacheSizeMask": {
		0x0:       "None",
		0x1000000: "Short",
		0x2000000: "Middle",
		0x3000000: "Long",
		0x4000000: "Max",
	},
	"CrPictureEffect": {
		0x0:   "Off",
		0x1:   "ToyCameraNormal",
		0x2:   "ToyCameraCool",
		0x3:   "ToyCameraWarm",
		0x4:   "ToyCameraGreen",
		0x5:   "ToyCameraMagenta",
		0x100: "Pop",
		0x200: "PosterizationBW",
		0x201: "PosterizationColor",
		0x300: "Retro",
		0x400: "SoftHighkey",
		0x500: "PartColorRed",
		0x501: "PartColorGreen",
		0x502: "PartColorBlue",
		0x503: "PartColorYellow",
		0x600: "HighContrastMonochrome",
		0x700: "SoftFocusLow",
		0x701: "SoftFocusMid",
		0x702: "SoftFocusHigh",
		0x800: "HDRPaintingLow",
		0x801: "HDRPaintingMid",
		0x802: "HDRPaintingHigh",
		0x901: "RichToneMonochrome",
		0xA00: "MiniatureAuto",
		0xA01: "MiniatureTop",
		0xA02: "MiniatureMidHorizontal",
		0xA03: "MiniatureBottom",
		0xA04: "MiniatureLeft",
		0xA05: "MiniatureMidVertical",
		0xA06: "MiniatureRight",
		0xB00: "MiniatureWaterColor",
		0xC00: "MiniatureIllustrationLow",
		0xC01: "MiniatureIllustrationMid",
		0xC02: "MiniatureIllustrationHigh",
	},
	"CrPictureProfile": {
		0x0:  "Off",
		0x1:  "Number1",
		0x2:  "Number2",
		0x3:  "Number3",
		0x4:  "Number4",
		0x5:  "Number5",
		0x6:  "Number6",
		0x7:  "Number7",
		0x8:  "Number8",
		0x9:  "Number9",
		0xA:  "Number10",
		0xB:  "Number11",
		0x41: "LUT_Number1",
		0x42: "LUT_Number2",
		0x43: "LUT_Number3",
		0x44: "LUT_Number4",
	},
	"CrPictureProfileBlackGammaRange": {
		0x1: "Wide",
		0x2: "Middle",
		0x3: "Narrow",
	},
	"CrPictureProfileDetailAdjustMode": {
		0x1: "Auto",
		0x2: "Manual",
	},
	"CrPictureProfileGamma": {
		0x1:   "Movie",
		0x2:   "Still",
		0x3:   "S_Cinetone",
		0x101: "Cine1",
		0x102: "Cine2",
		0x103: "Cine3",
		0x104: "Cine4",
		0x201: "ITU709",
		0x202: "ITU709_800",
		0x302: "S_Log2",
		0x303: "S_Log3",
		0x401: "HLG",
		0x402: "HLG1",
		0x403: "HLG2",
		0x404: "HLG3",
	},
	"CrPictureProfileKneeAutoSetSensitivity": {
		0x1: "Low",
		0x2: "Mid",
		0x3: "High",
	},
	"CrPictureProfileKneeMode": {
		0x1: "Auto",
		0x2: "Manual",
	},
	"CrPictureProfileKneeSetPoint": {
		0x0: "Invalid",
	},
	"CrPictureProfileResetEnableStatus": {
		0x0: "PictureProfileReset_Disable",
		0x1: "PictureProfileReset_Enable",
	},
	"CrPixelMappingEnableStatus": {
		0x0: "PixelMapping_Disable",
		0x1: "PixelMapping_Enable",
	},
	"CrPlaySetOfMultiMedia": {
		0x1: "Slot1",
		0x2: "Slot2",
	},
	"CrPlaybackContentsGammaType": {
		0x1:    "S_Gamut3_S_Log3",
		0x2:    "S_Gamut3_Cine_S_Log3",
		0x3:    "BT2020_HLG",
		0x4:    "BT2020_S_Log3",
		0xFFFF: "Others",
	},
	"CrPlaybackContentsRecordingFileFormat": {
		0x1B: "XAVC_HS_L_422",
		0x1C: "XAVC_HS_L_420",
		0x1D: "XAVC_S_L_422",
		0x1E: "XAVC_S_L_420",
		0x1F: "XAVC_S_I_422",
		0x20: "MPEG_HD_422",
	},
	"CrPlaybackContentsRecordingFrameRate": {
		0x1:  "120p",
		0x2:  "100p",
		0x3:  "60p",
		0x4:  "50p",
		0x5:  "30p",
		0x6:  "25p",
		0x7:  "24p",
		0x8:  "23_98p",
		0x9:  "29_97p",
		0xA:  "59_94p",
		0xB:  "19_98p",
		0xC:  "14_99p",
		0xD:  "12_50p",
		0xE:  "12_00p",
		0xF:  "11_99p",
		0x10: "10_00p",
		0x11: "9_99p",
		0x12: "6_00p",
		0x13: "5_99p",
		0x14: "5_00p",
		0x15: "4_995p",
		0x16: "24_00p",
		0x17: "119_88p",
		0x41: "120i",
		0x42: "100i",
		0x43: "60i",
		0x44: "50i",
		0x45: "30i",
		0x46: "25i",
		0x47: "24i",
		0x48: "23_98i",
		0x49: "29_97i",
		0x4A: "59_94i",
		0x4B: "19_98i",
		0x4C: "14_99i",
		0x4D: "12_50i",
		0x4E: "12_00i",
		0x4F: "11_99i",
		0x50: "10_00i",
		0x51: "9_99i",
		0x52: "6_00i",
		0x53: "5_99i",
		0x54: "5_00i",
		0x55: "4_995i",
		0x56: "24_00i",
		0x57: "119_88i",
	},
	"CrPlaybackMedia": {
		0x1: "Slot1",
		0x2: "Slot2",
	},
	"CrPlaybackViewMode": {
		0x1: "Playback",
		0x2: "Index",
	},
	"CrPostViewTransferResourceStatus": {
		0x1: "Available",
		0x2: "Unavailable",
	},
	"CrPowerSource": {
		0x1: "DC",
		0x2: "Battery",
		0x3: "PoE",
	},
	"CrPreAF": {
		0x1: "Off",
		0x2: "On",
	},
	"CrPresetPTZFSettingType": {
		0x1: "current",
	},
	"CrPresetPTZFThumbnail": {
		0x0: "Off",
		0x1: "On",
	},
	"CrPriorityKeySettings": {
		0x1: "PriorityKey_CameraPosition",
		0x2: "PriorityKey_PCRemote",
	},
	"CrPrioritySetInAF": {
		0x1: "AF",
		0x2: "Release",
		0x3: "BalancedEmphasis",
	},
	"CrPrioritySetInAWB": {
		0x1: "Standard",
		0x2: "Ambience",
		0x3: "White",
	},
	"CrProductShowcaseSet": {
		0x1: "Off",
		0x2: "On",
	},
	"CrProgramShiftStatus": {
		0x1: "Idle",
		0x2: "ProgramShift",
	},
	"CrPropValueSet": {
		0xFFFFFFFFFFFFFFFF: "PropValueMinus1",
		0x1:                "PropValuePlus1",
	},
	"CrPropertyCustomWBCaptureButton": {
		0x0: "PropertyCustomWBCapture_Up",
		0x1: "PropertyCustomWBCapture_Down",
	},
	"CrPropertyCustomWBExecutionState": {
		0x0: "Invalid",
		0x1: "Standby",
		0x2: "Capturing",
		0x3: "OperatingCamera",
	},
	"CrPropertyCustomWBOperation": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrPropertyEnableFlag": {
		0xFFFFFFFFFFFFFFFF: "EnableValue_NotSupported",
		0x0:                "EnableValue_False",
		0x1:                "EnableValue_True",
		0x2:                "EnableValue_DisplayOnly",
		0x3:                "EnableValue_SetOnly",
	},
	"CrPropertyLiveViewImageQuality": {
		0x0: "Low",
		0x1: "High",
	},
	"CrPropertyRAWJPCSaveImage": {
		0x0: "RAWAndJPEG",
		0x1: "JPEGOnly",
		0x2: "RAWOnly",
		0x3: "RAWAndHEIF",
		0x4: "HEIFOnly",
	},
	"CrPropertyStillImageTransSize": {
		0x0: "Original",
		0x1: "SmallSize",
	},
	"CrPropertyVariableFlag": {
		0x0: "EnableValue_Invalid",
		0x1: "EnableValue_Invariable",
		0x2: "EnableValue_Variable",
	},
	"CrProtectImageInFTPTransfer": {
		0x1: "Off",
		0x2: "On",
	},
	"CrProxyRecordingSetting": {
		0x0: "Invalid",
		0x1: "16M_420_10bit",
		0x2: "9M_420_10bit",
		0x3: "6M_420_8bit",
	},
	"CrPullPostViewImageStatus": {
		0x0: "NotExists",
		0x1: "Exists",
	},
	"CrPushAFModeSetting": {
		0x1: "ContinuousShotAF_C",
		0x2: "SingleShotAF_S",
	},
	"CrPushAGC": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrPushAutoFocus": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrPushAutoIris": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrPushAutoNDFilter": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrRAWFileCompressionType": {
		0x0: "RAWFile_Uncompression",
		0x1: "RAWFile_Compression",
		0x2: "RAWFile_LossLess",
		0x3: "RAWFile_LossLessS",
		0x4: "RAWFile_LossLessM",
		0x5: "RAWFile_LossLessL",
		0x6: "RAWFile_Compressed_HQ",
	},
	"CrRecognitionTarget": {
		0xFFFF: "Auto",
		0x1:    "Person",
		0x2:    "AnimalBird",
		0x3:    "Animal",
		0x4:    "Bird",
		0x5:    "Insect",
		0x6:    "CarTrain",
		0x7:    "Plane",
	},
	"CrRecordablePowerSources": {
		0x1: "DC",
		0x2: "Battery",
		0x3: "PoE",
	},
	"CrRecorderControlSetting": {
		0x0: "RecDisable",
		0x1: "RecEnable",
	},
	"CrRecorderSaveDestination": {
		0x1:  "External",
		0x10: "Internal",
		0x11: "ExternalAndInternal",
	},
	"CrRecorderStart": {
		0x0: "RecStartDisable",
		0x1: "RecStartEnable",
	},
	"CrRecorderStatus": {
		0x0: "Idle",
		0x1: "Ready",
		0x2: "PreparingToRecord",
		0x3: "Standby",
		0x4: "Recording",
		0x5: "Stopping",
	},
	"CrRecordingFileNumber": {
		0x1: "Reset",
		0x2: "Series",
	},
	"CrRecordingFolderFormat": {
		0x1: "Standard",
		0x2: "Date",
	},
	"CrRecordingFrameRateProxySettingMovie": {
		0x4:  "50p",
		0x6:  "25p",
		0x7:  "24p",
		0x8:  "23_98p",
		0x9:  "29_97p",
		0xA:  "59_94p",
		0x16: "24_00p",
		0x17: "119_88p",
	},
	"CrRecordingFrameRateSettingMovie": {
		0x1:  "120p",
		0x2:  "100p",
		0x3:  "60p",
		0x4:  "50p",
		0x5:  "30p",
		0x6:  "25p",
		0x7:  "24p",
		0x8:  "23_98p",
		0x9:  "29_97p",
		0xA:  "59_94p",
		0x16: "24_00p",
		0x17: "119_88p",
	},
	"CrRecordingMedia": {
		0x1:   "Slot1",
		0x2:   "Slot2",
		0x101: "SimultaneousRecording",
		0x102: "SortRecording",
	},
	"CrRecordingMediaMovie": {
		0x1:   "Slot1",
		0x2:   "Slot2",
		0x101: "SimultaneousRecording",
	},
	"CrRecordingSettingMovie": {
		0x0:  "Invalid",
		0x1:  "60p_50M",
		0x2:  "30p_50M",
		0x3:  "24p_50M",
		0x4:  "50p_50M",
		0x5:  "25p_50M",
		0x6:  "60i_24M",
		0x7:  "50i_24M_FX",
		0x8:  "60i_17M_FH",
		0x9:  "50i_17M_FH",
		0xA:  "60p_28M_PS",
		0xB:  "50p_28M_PS",
		0xC:  "24p_24M_FX",
		0xD:  "25p_24M_FX",
		0xE:  "24p_17M_FH",
		0xF:  "25p_17M_FH",
		0x10: "120p_50M_1280x720",
		0x11: "100p_50M_1280x720",
		0x12: "1920x1080_30p_16M",
		0x13: "1920x1080_25p_16M",
		0x14: "1280x720_30p_6M",
		0x15: "1280x720_25p_6M",
		0x16: "1920x1080_60p_28M",
		0x17: "1920x1080_50p_28M",
		0x18: "60p_25M_XAVC_S_HD",
		0x19: "50p_25M_XAVC_S_HD",
		0x1A: "30p_16M_XAVC_S_HD",
		0x1B: "25p_16M_XAVC_S_HD",
		0x1C: "120p_100M_1920x1080_XAVC_S_HD",
		0x1D: "100p_100M_1920x1080_XAVC_S_HD",
		0x1E: "120p_60M_1920x1080_XAVC_S_HD",
		0x1F: "100p_60M_1920x1080_XAVC_S_HD",
		0x20: "30p_100M_XAVC_S_4K",
		0x21: "25p_100M_XAVC_S_4K",
		0x22: "24p_100M_XAVC_S_4K",
		0x23: "30p_60M_XAVC_S_4K",
		0x24: "25p_60M_XAVC_S_4K",
		0x25: "24p_60M_XAVC_S_4K",
		0x26: "600M_422_10bit",
		0x27: "500M_422_10bit",
		0x28: "400M_420_10bit",
		0x29: "300M_422_10bit",
		0x2A: "280M_422_10bit",
		0x2B: "250M_422_10bit",
		0x2C: "240M_422_10bit",
		0x2D: "222M_422_10bit",
		0x2E: "200M_422_10bit",
		0x2F: "200M_420_10bit",
		0x30: "200M_420_8bit",
		0x31: "185M_422_10bit",
		0x32: "150M_420_10bit",
		0x33: "150M_420_8bit",
		0x34: "140M_422_10bit",
		0x35: "111M_422_10bit",
		0x36: "100M_422_10bit",
		0x37: "100M_420_10bit",
		0x38: "100M_420_8bit",
		0x39: "93M_422_10bit",
		0x3A: "89M_422_10bit",
		0x3B: "75M_420_10bit",
		0x3C: "60M_420_8bit",
		0x3D: "50M_422_10bit",
		0x3E: "50M_420_10bit",
		0x3F: "50M_420_8bit",
		0x40: "45M_420_10bit",
		0x41: "30M_420_10bit",
		0x42: "25M_420_8bit",
		0x43: "16M_420_8bit",
		0x44: "520M_422_10bit",
		0x45: "260M_422_10bit",
	},
	"CrRedEyeReduction": {
		0x0: "RedEye_Off",
		0x1: "RedEye_On",
	},
	"CrReleaseWithoutCard": {
		0x1: "Disable",
		0x2: "Enable",
	},
	"CrReleaseWithoutLens": {
		0x1: "Disable",
		0x2: "Enable",
	},
	"CrRemoconZoomSpeedType": {
		0x0: "Invalid",
		0x1: "Variable",
		0x2: "Fixed",
	},
	"CrRemoteKeySLOTSelectButton": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrRemoteKeyThumbnailButton": {
		0x1: "Up",
		0x2: "Down",
	},
	"CrRemoteSaveImageSize": {
		0x1: "LargeSize",
		0x2: "SmallSize",
	},
	"CrRemoteTouchOperationEnableStatus": {
		0x0: "RemoteTouchOperation_Disable",
		0x1: "RemoteTouchOperation_Enable",
	},
	"CrRightLeftEyeSelect": {
		0x1: "Auto",
		0x2: "RightEye",
		0x3: "LeftEye",
	},
	"CrSQFrameRate": {
		0x0: "Invalid",
	},
	"CrSQModeSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrSafetyZoneDisplay": {
		0xFF: "Off",
	},
	"CrSceneFileIndex": {
		0x0:  "Scene_None",
		0x1:  "Scene_1",
		0x2:  "Scene_2",
		0x3:  "Scene_3",
		0x4:  "Scene_4",
		0x5:  "Scene_5",
		0x6:  "Scene_6",
		0x7:  "Scene_7",
		0x8:  "Scene_8",
		0x9:  "Scene_9",
		0xA:  "Scene_10",
		0xB:  "Scene_11",
		0xC:  "Scene_12",
		0xD:  "Scene_13",
		0xE:  "Scene_14",
		0xF:  "Scene_15",
		0x10: "Scene_16",
	},
	"CrSceneFileOperationEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrSdkControlMode": {
		0x0: "Remote",
		0x1: "ContentsTransfer",
		0x2: "RemoteTransfer",
	},
	"CrSelectFTPServerID": {
		0xFFFFFFFF: "Nothing",
	},
	"CrSelectFinder": {
		0x1: "Auto",
		0x2: "ViewFinder_M",
		0x3: "Monitor_M",
		0x4: "Auto2",
	},
	"CrSelectFinderMonitor": {
		0x1: "Auto",
		0x2: "ViewFinder_M",
		0x3: "Monitor_M",
		0x4: "Auto2",
	},
	"CrSelectIPTCMetadata": {
		0x0: "Off",
	},
	"CrSelectUserBaseLookToEdit": {
		0x0: "Invalid",
	},
	"CrSelectUserBaseLookToSetInPPLUT": {
		0x0: "Invalid",
	},
	"CrSensorCleaningEnableStatus": {
		0x0: "SensorCleaning_Disable",
		0x1: "SensorCleaning_Enable",
	},
	"CrShootingEnableSettingLicense": {
		0x1: "Enable",
		0x2: "Disable",
	},
	"CrShootingSelfTimerStatus": {
		0x1: "Idle",
		0x2: "CountingDown",
	},
	"CrShutterECSSetting": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrShutterMode": {
		0x1: "Speed",
		0x2: "Angle",
	},
	"CrShutterModeSetting": {
		0x1: "ShutterMode_Automatic",
		0x2: "ShutterMode_Manual",
	},
	"CrShutterModeStatus": {
		0x1: "Off",
		0x2: "Speed",
		0x3: "Angle",
		0x4: "ECS",
		0x5: "Auto",
	},
	"CrShutterReleaseTimeLagControl": {
		0x1: "Off",
		0x2: "On_Stability",
		0x3: "On_Fastest",
	},
	"CrShutterSelectMode": {
		0x1: "Step",
		0x2: "Continue",
	},
	"CrShutterSetting": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrShutterSlow": {
		0x1: "Off",
		0x2: "On",
	},
	"CrShutterSpeedSet": {
		0x0:        "ShutterSpeed_Bulb",
		0xFFFFFFFF: "ShutterSpeed_Nothing",
	},
	"CrShutterType": {
		0x1: "Auto",
		0x2: "MechanicalShutter",
		0x3: "ElectronicShutter",
	},
	"CrSignalShootingTimingPreNotificationMode": {
		0x1: "SignalShootingTimingPreNotification_Off",
		0x2: "SignalShootingTimingPreNotification_On",
	},
	"CrSilentMode": {
		0x1: "Off",
		0x2: "On",
	},
	"CrSilentModeApertureDriveInAF": {
		0x1: "NotTarget",
		0x2: "Standard",
		0x3: "SilentPriority",
	},
	"CrSilentModeAutoPixelMapping": {
		0x1: "NotTarget",
		0x2: "Off",
	},
	"CrSilentModeShutterWhenPowerOff": {
		0x1: "NotTarget",
		0x2: "Off",
	},
	"CrSimulRecSetting": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrSimulRecSettingMovieRecButton": {
		0x1: "SlotAB_SlotAB",
		0x2: "SlotA_SlotB",
		0x3: "SlotB_SlotA",
	},
	"CrSlotNumber": {
		0x1: "Slot1",
		0x2: "Slot2",
	},
	"CrSlotStatus": {
		0x0: "OK",
		0x1: "NoCard",
		0x2: "CardError",
		0x3: "RecognizingOrLockedError",
		0x4: "DBError",
		0x5: "CardRecognizing",
		0x6: "CardLockedAndDBError",
		0x7: "DBError_CantRepairAndNeedFormat",
		0x8: "CardError_ReadOnlyMedia",
	},
	"CrSoftSkinEffect": {
		0x1: "Off",
		0x2: "Low",
		0x3: "Mid",
		0x4: "High",
	},
	"CrStillImageStoreDestination": {
		0x1: "HostPC",
		0x2: "MemoryCard",
		0x3: "HostPCAndMemoryCard",
	},
	"CrStreamButtonEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrStreamCipherType": {
		0x1: "None",
		0x2: "AES_128",
		0x3: "AES_192",
		0x4: "AES_256",
	},
	"CrStreamModeSetting": {
		0x1: "Undefined",
		0x2: "Caller",
		0x3: "Listener",
		0x4: "Rendezvous",
	},
	"CrStreamSettingListOperationStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrStreamStatus": {
		0x1: "Inactive",
		0x2: "Idle",
		0x3: "Streaming",
		0x4: "Error",
		0x5: "Ready",
	},
	"CrSubjectRecognitionAF": {
		0x1: "Off",
		0x2: "OnlyAF",
		0x3: "PriorityAF",
	},
	"CrSubjectRecognitionAnimalBirdDetectionParts": {
		0xFF: "FollowIndividualSetting",
		0x1:  "EyeHeadBody",
		0x2:  "EyeHead",
		0x3:  "Eye",
	},
	"CrSubjectRecognitionAnimalBirdPriority": {
		0x1: "Auto",
		0x2: "AnimalPriority",
		0x3: "BirdPriority",
	},
	"CrSubjectRecognitionInAF": {
		0x1: "Off",
		0x2: "On",
	},
	"CrSubjectRecognitionPriorityOnRegisteredFace": {
		0x1: "Off",
		0x2: "On",
	},
	"CrSynchroterminalForcedOutput": {
		0x1: "Off",
		0x2: "On",
	},
	"CrSystemErrorCautionStatus": {
		0x1: "NoError",
		0x2: "Error",
	},
	"CrTCUBDisplaySetting": {
		0x1: "Counter",
		0x2: "TC",
		0x3: "UB",
		0x4: "Duration",
	},
	"CrTallyLampControl": {
		0x1: "Off",
		0x2: "On",
	},
	"CrTiltLimitMode": {
		0x1: "Off",
		0x2: "On",
	},
	"CrTiltPositionStatus": {
		0x1: "Idle",
		0x2: "Moving",
		0x3: "Unknown",
		0x4: "Uninitialized",
	},
	"CrTimeCodeFormat": {
		0x1: "DF",
		0x2: "NDF",
	},
	"CrTimeCodeMake": {
		0x1: "Preset",
		0x2: "Regenerate",
	},
	"CrTimeCodePresetResetEnableStatus": {
		0x0: "TimeCodePresetReset_Disable",
		0x1: "TimeCodePresetReset_Enable",
	},
	"CrTimeCodeRun": {
		0x1: "RecRun",
		0x2: "FreeRun",
	},
	"CrTimeShiftShooting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrTimeShiftShootingStatus": {
		0x1: "Idle",
		0x2: "TimeShiftShooting",
		0x3: "Impossible",
		0x4: "Impossible_TimerShiftOverheating",
		0x5: "MainShooting",
	},
	"CrTimeShiftTriggerSetting": {
		0x1: "S1AndAF",
		0x2: "S1",
		0x3: "AF",
	},
	"CrTimeZoneSettingExists": {
		0x0: "False",
		0x1: "True",
	},
	"CrTnumber": {
		0xFFFD: "IrisClose",
		0xFFFE: "Unknown",
		0xFFFF: "Nothing",
	},
	"CrTopOfTheGroupShootingMarkSetting": {
		0x0:   "None",
		0x1:   "Rating1",
		0x2:   "Rating2",
		0x3:   "Rating3",
		0x4:   "Rating4",
		0x5:   "Rating5",
		0x101: "DividerFrame",
	},
	"CrTouchFunctionInMF": {
		0x1: "TrackingAF",
		0x2: "SpotFocus",
	},
	"CrTouchOperation": {
		0x1: "Off",
		0x2: "On",
		0x3: "PlaybackOnly",
	},
	"CrTrackingFrameType": {
		0x0: "Unknown",
		0x1: "NonTargetAF",
		0x2: "TargetAF",
	},
	"CrTrackingOnAndAFOnEnableStatus": {
		0x0: "Disable",
		0x1: "Enable",
	},
	"CrUSBPowerSupply": {
		0x1: "Off",
		0x2: "On",
		0x3: "Auto",
		0x4: "Port1",
		0x5: "Port2",
	},
	"CrUpdateStatus": {
		0x1:   "NoError",
		0x101: "OtherError",
		0x102: "NoUpdateFileInMedia",
		0x103: "FileVersionOlder",
		0x104: "FileDamaged",
		0x105: "FileInvalidData",
		0x106: "FileModelNotMatch",
		0x107: "FileRegionNotMatch",
		0x108: "FileVersionNotMatch",
		0x109: "LowBattery",
		0x10A: "UnsupportedBattery",
	},
	"CrUploadPartialDataType": {
		0x50001: "FirmwareData",
	},
	"CrUploadSettingFileType": {
		0x1000: "Setup",
		0x1002: "FTPTransferSetting",
	},
	"CrUserBaseLookInput": {
		0x1: "S_Gamut3_SLog3",
		0x2: "S_Gamut3_Cine_SLog3",
	},
	"CrUserBaseLookOutput": {
		0x1:   "BT709",
		0x2:   "BT709_Legal",
		0x101: "HLG",
		0x102: "HLG_Legal",
	},
	"CrUserBitPresetResetEnableStatus": {
		0x0: "UserBitPresetReset_Disable",
		0x1: "UserBitPresetReset_Enable",
	},
	"CrUserBitTimeRec": {
		0x1: "Off",
		0x2: "On",
	},
	"CrValidRecordingVideoFormat_Bitrate": {
		0x0:   "None",
		0x100: "35Mbps",
		0x200: "50Mbps",
		0x300: "25Mbps",
	},
	"CrValidRecordingVideoFormat_Resolution": {
		0x0: "None",
		0x1: "1920x1080",
		0x2: "3840x2160",
		0x3: "4096x2160",
		0x4: "1280x720",
	},
	"CrValidRecordingVideoFormat_ScanLineType": {
		0x0:     "Progressive",
		0x10000: "Interlace",
	},
	"CrVideoRecordingFormatBitrateSetting": {
		0x0: "None",
	},
	"CrVideoRecordingFormatQuality": {
		0x1: "Level1",
		0x2: "Level2",
		0x3: "Level3",
	},
	"CrVideoStreamAdaptiveRateControl": {
		0x1: "Off",
		0x2: "On",
	},
	"CrVideoStreamBitRateCompressionMode": {
		0x1: "ConstantBitRate_CBR",
		0x2: "VariableBitRate_VBR",
	},
	"CrVideoStreamBitRateVBRMode": {
		0x1: "Standard",
		0x2: "BitRateLimit",
	},
	"CrVideoStreamCodec": {
		0x1: "Off",
		0x2: "MotionJpeg",
		0x3: "H264",
		0x4: "H265",
	},
	"CrVideoStreamMovieRecPermission": {
		0x1: "NotPermitted",
		0x2: "Permitted",
	},
	"CrVideoStreamResolutionMethod": {
		0x1: "Manualmode",
		0x2: "Easymode",
	},
	"CrVideoStreamSettingProtocol": {
		0x0: "None",
	},
	"CrWakeOnLAN": {
		0x1: "Off",
		0x2: "On",
	},
	"CrWhiteBalanceInitialize": {
		0x1: "WhiteBalance_Initialized",
	},
	"CrWhiteBalanceModeSetting": {
		0x1: "Automatic",
		0x2: "Manual",
	},
	"CrWhiteBalanceOffsetSetting": {
		0x1: "Off",
		0x2: "On",
	},
	"CrWhiteBalanceSetting": {
		0x0:   "WhiteBalance_AWB",
		0x1:   "WhiteBalance_Underwater_Auto",
		0x11:  "WhiteBalance_Daylight",
		0x12:  "WhiteBalance_Shadow",
		0x13:  "WhiteBalance_Cloudy",
		0x14:  "WhiteBalance_Tungsten",
		0x20:  "WhiteBalance_Fluorescent",
		0x21:  "WhiteBalance_Fluorescent_WarmWhite",
		0x22:  "WhiteBalance_Fluorescent_CoolWhite",
		0x23:  "WhiteBalance_Fluorescent_DayWhite",
		0x24:  "WhiteBalance_Fluorescent_Daylight",
		0x30:  "WhiteBalance_Flush",
		0x100: "WhiteBalance_ColorTemp",
		0x101: "WhiteBalance_Custom_1",
		0x102: "WhiteBalance_Custom_2",
		0x103: "WhiteBalance_Custom_3",
		0x104: "WhiteBalance_Custom",
	},
	"CrWhiteBalanceSwitch": {
		0x1: "PresetMode",
		0x2: "MemoryAMode",
		0x3: "MemoryBMode",
	},
	"CrWindNoiseReductForExternalMic": {
		0x1: "OFF",
		0x2: "ON",
	},
	"CrWindNoiseReduction": {
		0x1: "Off",
		0x2: "On",
		0x3: "Auto",
	},
	"CrWirelessFlash": {
		0x0: "Off",
		0x1: "On",
	},
	"CrWriteCopyrightInfo": {
		0x1: "Off",
		0x2: "On",
	},
	"CrZebraDisplay": {
		0x1: "Off",
		0x2: "On",
	},
	"CrZebraLevel": {
		0x1000: "LowerLimitOffset",
		0x8000: "CustomOffset",
	},
	"CrZebraLevelTypeCustom": {
		0x1: "StdAndRange",
		0x2: "LowerLimit",
	},
	"CrZoomAndFocusPresetExist": {
		0x1: "False",
		0x2: "True",
	},
	"CrZoomAndFocusPresetZoomOnlyEnableStatus": {
		0x1: "Disable",
		0x2: "Enable",
	},
	"CrZoomAndFocusPresetZoomOnlyValue": {
		0x1: "Off",
		0x2: "On",
	},
	"CrZoomDistanceUnitSetting": {
		0x1: "mm",
		0x2: "percent",
	},
	"CrZoomDrivingStatus": {
		0x1: "NotDriving",
		0x2: "Driving",
	},
	"CrZoomOperation": {
		0xFFFFFFFFFFFFFFFF: "Wide",
		0x0:                "Stop",
		0x1:                "Tele",
	},
	"CrZoomOperationEnableStatus": {
		0x0: "Default",
		0x1: "Enable",
	},
	"CrZoomSettingType": {
		0x1: "ZoomSetting_OpticalZoomOnly",
		0x2: "ZoomSetting_SmartZoomOnly",
		0x3: "ZoomSetting_On_ClearImageZoom",
		0x4: "ZoomSetting_On_DigitalZoom",
	},
	"CrZoomTypeStatus": {
		0x1: "OpticalZoom",
		0x2: "SmartZoom",
		0x3: "ClearImageZoom",
		0x4: "DigitalZoom",
	},
}

// autoBoundEnums binds a property to an enum where the SDK's own names match
// exactly (CrFileType -> PropFileType). Anything less certain is left to the
// hand-written table in values.go.
var autoBoundEnums = map[Prop]string{
	PropFileType:                                   "CrFileType",
	PropFocusMode:                                  "CrFocusMode",
	PropMeteringMode:                               "CrMeteringMode",
	PropFlashMode:                                  "CrFlashMode",
	PropWirelessFlash:                              "CrWirelessFlash",
	PropRedEyeReduction:                            "CrRedEyeReduction",
	PropDriveMode:                                  "CrDriveMode",
	PropImageSize:                                  "CrImageSize",
	PropPictureEffect:                              "CrPictureEffect",
	PropFocusArea:                                  "CrFocusArea",
	PropColortemp:                                  "CrColortemp",
	PropLiveViewDisplayEffect:                      "CrLiveViewDisplayEffect",
	PropStillImageStoreDestination:                 "CrStillImageStoreDestination",
	PropPriorityKeySettings:                        "CrPriorityKeySettings",
	PropAFTrackingSensitivity:                      "CrAFTrackingSensitivity",
	PropIrisModeSetting:                            "CrIrisModeSetting",
	PropShutterModeSetting:                         "CrShutterModeSetting",
	PropGainControlSetting:                         "CrGainControlSetting",
	PropGainBaseIsoSensitivity:                     "CrGainBaseIsoSensitivity",
	PropGainBaseSensitivity:                        "CrGainBaseSensitivity",
	PropPlaybackMedia:                              "CrPlaybackMedia",
	PropDispMode:                                   "CrDispMode",
	PropTouchOperation:                             "CrTouchOperation",
	PropSelectFinderMonitor:                        "CrSelectFinderMonitor",
	PropAutoPowerOffTemperature:                    "CrAutoPowerOffTemperature",
	PropBodyKeyLock:                                "CrBodyKeyLock",
	PropExposureCtrlType:                           "CrExposureCtrlType",
	PropMonitorLUTSetting:                          "CrMonitorLUTSetting",
	PropFocalDistanceUnitSetting:                   "CrFocalDistanceUnitSetting",
	PropZoomDistanceUnitSetting:                    "CrZoomDistanceUnitSetting",
	PropShutterModeStatus:                          "CrShutterModeStatus",
	PropShutterSlow:                                "CrShutterSlow",
	PropBatteryRemainDisplayUnit:                   "CrBatteryRemainDisplayUnit",
	PropPowerSource:                                "CrPowerSource",
	PropMovieShootingMode:                          "CrMovieShootingMode",
	PropMovieShootingModeColorGamut:                "CrMovieShootingModeColorGamut",
	PropMovieShootingModeTargetDisplay:             "CrMovieShootingModeTargetDisplay",
	PropDepthOfFieldAdjustmentMode:                 "CrDepthOfFieldAdjustmentMode",
	PropWhiteBalanceModeSetting:                    "CrWhiteBalanceModeSetting",
	PropShutterECSSetting:                          "CrShutterECSSetting",
	PropFocusModeSetting:                           "CrFocusModeSetting",
	PropShutterSetting:                             "CrShutterSetting",
	PropShutterMode:                                "CrShutterMode",
	PropNDFilter:                                   "CrNDFilter",
	PropNDFilterModeSetting:                        "CrNDFilterModeSetting",
	PropNDFilterValue:                              "CrNDFilterValue",
	PropGainUnitSetting:                            "CrGainUnitSetting",
	PropAWB:                                        "CrAWB",
	PropSceneFileIndex:                             "CrSceneFileIndex",
	PropSubjectRecognitionAF:                       "CrSubjectRecognitionAF",
	PropAFAssist:                                   "CrAFAssist",
	PropNDFilterSwitchingSetting:                   "CrNDFilterSwitchingSetting",
	PropFunctionOfRemoteTouchOperation:             "CrFunctionOfRemoteTouchOperation",
	PropExtendedInterfaceMode:                      "CrExtendedInterfaceMode",
	PropSQFrameRate:                                "CrSQFrameRate",
	PropAudioRecording:                             "CrAudioRecording",
	PropTimeCodeFormat:                             "CrTimeCodeFormat",
	PropTimeCodeRun:                                "CrTimeCodeRun",
	PropTimeCodeMake:                               "CrTimeCodeMake",
	PropUserBitTimeRec:                             "CrUserBitTimeRec",
	PropImageStabilizationSteadyShot:               "CrImageStabilizationSteadyShot",
	PropSilentMode:                                 "CrSilentMode",
	PropSilentModeApertureDriveInAF:                "CrSilentModeApertureDriveInAF",
	PropSilentModeShutterWhenPowerOff:              "CrSilentModeShutterWhenPowerOff",
	PropSilentModeAutoPixelMapping:                 "CrSilentModeAutoPixelMapping",
	PropShutterType:                                "CrShutterType",
	PropPictureProfile:                             "CrPictureProfile",
	PropCreativeLook:                               "CrCreativeLook",
	PropProxyRecordingSetting:                      "CrProxyRecordingSetting",
	PropFunctionOfTouchOperation:                   "CrFunctionOfTouchOperation",
	PropHighResolutionShutterSpeedSetting:          "CrHighResolutionShutterSpeedSetting",
	PropDeleteUserBaseLook:                         "CrDeleteUserBaseLook",
	PropSelectUserBaseLookToEdit:                   "CrSelectUserBaseLookToEdit",
	PropSelectUserBaseLookToSetInPPLUT:             "CrSelectUserBaseLookToSetInPPLUT",
	PropUserBaseLookInput:                          "CrUserBaseLookInput",
	PropFlickerLessShooting:                        "CrFlickerLessShooting",
	PropAudioLevelDisplay:                          "CrAudioLevelDisplay",
	PropAutoReview:                                 "CrAutoReview",
	PropAudioSignals:                               "CrAudioSignals",
	PropMonitoringOutputDisplayHDMI:                "CrMonitoringOutputDisplayHDMI",
	PropEframingScaleAuto:                          "CrEframingScaleAuto",
	PropEframingModeAuto:                           "CrEframingModeAuto",
	PropEframingRecordingImageCrop:                 "CrEframingRecordingImageCrop",
	PropEframingHDMICrop:                           "CrEframingHDMICrop",
	PropCameraEframing:                             "CrCameraEframing",
	PropUSBPowerSupply:                             "CrUSBPowerSupply",
	PropLongExposureNR:                             "CrLongExposureNR",
	PropHighIsoNR:                                  "CrHighIsoNR",
	PropHLGStillImage:                              "CrHLGStillImage",
	PropColorSpace:                                 "CrColorSpace",
	PropBracketOrder:                               "CrBracketOrder",
	PropFocusBracketOrder:                          "CrFocusBracketOrder",
	PropFocusBracketExposureLock1stImg:             "CrFocusBracketExposureLock1stImg",
	PropFocusBracketIntervalUntilNextShot:          "CrFocusBracketIntervalUntilNextShot",
	PropElectricFrontCurtainShutter:                "CrElectricFrontCurtainShutter",
	PropBulbTimerSetting:                           "CrBulbTimerSetting",
	PropAutoSlowShutter:                            "CrAutoSlowShutter",
	PropIsoAutoMinShutterSpeedMode:                 "CrIsoAutoMinShutterSpeedMode",
	PropIsoAutoMinShutterSpeedManual:               "CrIsoAutoMinShutterSpeedManual",
	PropIsoAutoMinShutterSpeedPreset:               "CrIsoAutoMinShutterSpeedPreset",
	PropSoftSkinEffect:                             "CrSoftSkinEffect",
	PropFocusMagnificationTime:                     "CrFocusMagnificationTime",
	PropSubjectRecognitionInAF:                     "CrSubjectRecognitionInAF",
	PropRecognitionTarget:                          "CrRecognitionTarget",
	PropRightLeftEyeSelect:                         "CrRightLeftEyeSelect",
	PropSelectFTPServerID:                          "CrSelectFTPServerID",
	PropNDFilterUnitSetting:                        "CrNDFilterUnitSetting",
	PropNDFilterOpticalDensityValue:                "CrNDFilterOpticalDensityValue",
	PropIrisDisplayUnit:                            "CrIrisDisplayUnit",
	PropImageStabilizationSteadyShotAdjust:         "CrImageStabilizationSteadyShotAdjust",
	PropExtendedShutterSpeed:                       "CrExtendedShutterSpeed",
	PropCameraButtonFunction:                       "CrCameraButtonFunction",
	PropCameraDialFunction:                         "CrCameraDialFunction",
	PropSynchroterminalForcedOutput:                "CrSynchroterminalForcedOutput",
	PropShutterReleaseTimeLagControl:               "CrShutterReleaseTimeLagControl",
	PropTimeShiftShooting:                          "CrTimeShiftShooting",
	PropTimeShiftTriggerSetting:                    "CrTimeShiftTriggerSetting",
	PropEmbedLUTFile:                               "CrEmbedLUTFile",
	PropAPSCS35:                                    "CrAPS_C_S35",
	PropLensCompensationShading:                    "CrLensCompensationShading",
	PropLensCompensationChromaticAberration:        "CrLensCompensationChromaticAberration",
	PropLensCompensationDistortion:                 "CrLensCompensationDistortion",
	PropLensCompensationBreathing:                  "CrLensCompensationBreathing",
	PropRecordingMedia:                             "CrRecordingMedia",
	PropAutoSwitchMedia:                            "CrAutoSwitchMedia",
	PropRecordingFileNumber:                        "CrRecordingFileNumber",
	PropRecordingFolderFormat:                      "CrRecordingFolderFormat",
	PropSelectIPTCMetadata:                         "CrSelectIPTCMetadata",
	PropWriteCopyrightInfo:                         "CrWriteCopyrightInfo",
	PropFocusBracketRecordingFolder:                "CrFocusBracketRecordingFolder",
	PropReleaseWithoutLens:                         "CrReleaseWithoutLens",
	PropReleaseWithoutCard:                         "CrReleaseWithoutCard",
	PropGridLineDisplay:                            "CrGridLineDisplay",
	PropFacePriorityInMultiMetering:                "CrFacePriorityInMultiMetering",
	PropPrioritySetInAWB:                           "CrPrioritySetInAWB",
	PropAFIlluminator:                              "CrAFIlluminator",
	PropApertureDriveInAF:                          "CrApertureDriveInAF",
	PropAFWithShutter:                              "CrAFWithShutter",
	PropFullTimeDMF:                                "CrFullTimeDMF",
	PropPreAF:                                      "CrPreAF",
	PropSubjectRecognitionAnimalBirdPriority:       "CrSubjectRecognitionAnimalBirdPriority",
	PropSubjectRecognitionAnimalBirdDetectionParts: "CrSubjectRecognitionAnimalBirdDetectionParts",
	PropSubjectRecognitionPriorityOnRegisteredFace: "CrSubjectRecognitionPriorityOnRegisteredFace",
	PropFaceEyeFrameDisplay:                        "CrFaceEyeFrameDisplay",
	PropFocusMap:                                   "CrFocusMap",
	PropAFInFocusMagnifier:                         "CrAFInFocusMagnifier",
	PropAFTrackForSpeedChange:                      "CrAFTrackForSpeedChange",
	PropPlaySetOfMultiMedia:                        "CrPlaySetOfMultiMedia",
	PropRemoteSaveImageSize:                        "CrRemoteSaveImageSize",
	PropProtectImageInFTPTransfer:                  "CrProtectImageInFTPTransfer",
	PropMonitorBrightnessType:                      "CrMonitorBrightnessType",
	PropTCUBDisplaySetting:                         "CrTCUBDisplaySetting",
	PropGammaDisplayAssist:                         "CrGammaDisplayAssist",
	PropGammaDisplayAssistType:                     "CrGammaDisplayAssistType",
	PropAudioSignalsStartEnd:                       "CrAudioSignalsStartEnd",
	PropControlForHDMI:                             "CrControlForHDMI",
	PropAntidustShutterWhenPowerOff:                "CrAntidustShutterWhenPowerOff",
	PropWakeOnLAN:                                  "CrWakeOnLAN",
	PropBatteryLevel:                               "CrBatteryLevel",
	PropLiveViewStatus:                             "CrLiveViewStatus",
	PropCameraSettingsResetEnableStatus:            "CrCameraSettingsResetEnableStatus",
	PropAPSCOrFullSwitchingSetting:                 "CrAPS_C_or_Full_SwitchingSetting",
	PropAPSCOrFullSwitchingEnableStatus:            "CrAPS_C_or_Full_SwitchingEnableStatus",
	PropNDFilterMode:                               "CrNDFilterMode",
	PropMoviePlayingSpeed:                          "CrMoviePlayingSpeed",
	PropMoviePlayingState:                          "CrMoviePlayingState",
	PropFocusTouchSpotStatus:                       "CrFocusTouchSpotStatus",
	PropFocusTrackingStatus:                        "CrFocusTrackingStatus",
	PropDepthOfFieldAdjustmentInterlockingMode:     "CrDepthOfFieldAdjustmentInterlockingMode",
	PropRecorderSaveDestination:                    "CrRecorderSaveDestination",
	PropCurrentSceneFileEdited:                     "CrCurrentSceneFileEdited",
	PropMovieRecButtonToggleEnableStatus:           "CrMovieRecButtonToggleEnableStatus",
	PropRemoteTouchOperationEnableStatus:           "CrRemoteTouchOperationEnableStatus",
	PropCancelRemoteTouchOperationEnableStatus:     "CrCancelRemoteTouchOperationEnableStatus",
	PropLensInformationEnableStatus:                "CrLensInformationEnableStatus",
	PropFocusBracketShootingStatus:                 "CrFocusBracketShootingStatus",
	PropPixelMappingEnableStatus:                   "CrPixelMappingEnableStatus",
	PropTimeCodePresetResetEnableStatus:            "CrTimeCodePresetResetEnableStatus",
	PropUserBitPresetResetEnableStatus:             "CrUserBitPresetResetEnableStatus",
	PropSensorCleaningEnableStatus:                 "CrSensorCleaningEnableStatus",
	PropPictureProfileResetEnableStatus:            "CrPictureProfileResetEnableStatus",
	PropCreativeLookResetEnableStatus:              "CrCreativeLookResetEnableStatus",
	PropDeviceOverheatingState:                     "CrDeviceOverheatingState",
	PropHighResolutionShutterSpeed:                 "CrHighResolutionShutterSpeed",
	PropBaseLookImportOperationEnableStatus:        "CrBaseLookImportOperationEnableStatus",
	PropFocusDrivingStatus:                         "CrFocusDrivingStatus",
	PropFlickerScanStatus:                          "CrFlickerScanStatus",
	PropFlickerScanEnableStatus:                    "CrFlickerScanEnableStatus",
	PropFTPServerSettingOperationEnableStatus:      "CrFTPServerSettingOperationEnableStatus",
	PropCameraShakeStatus:                          "CrCameraShakeStatus",
	PropCameraOperatingMode:                        "CrCameraOperatingMode",
	PropPlaybackViewMode:                           "CrPlaybackViewMode",
	PropMonitoringDeliveringStatus:                 "CrMonitoringDeliveringStatus",
	PropMonitoringIsDelivering:                     "CrMonitoringIsDelivering",
	PropCameraErrorCautionStatus:                   "CrCameraErrorCautionStatus",
	PropSystemErrorCautionStatus:                   "CrSystemErrorCautionStatus",
	PropCameraButtonFunctionStatus:                 "CrCameraButtonFunctionStatus",
	PropFlickerLessShootingStatus:                  "CrFlickerLessShootingStatus",
	PropContinuousShootingSpotBoostStatus:          "CrContinuousShootingSpotBoostStatus",
	PropContinuousShootingSpotBoostEnableStatus:    "CrContinuousShootingSpotBoostEnableStatus",
	PropTimeShiftShootingStatus:                    "CrTimeShiftShootingStatus",
	PropZoomDrivingStatus:                          "CrZoomDrivingStatus",
	PropShootingSelfTimerStatus:                    "CrShootingSelfTimerStatus",
	PropCreateNewFolderEnableStatus:                "CrCreateNewFolderEnableStatus",
	PropTrackingOnAndAFOnEnableStatus:              "CrTrackingOnAndAFOnEnableStatus",
	PropProgramShiftStatus:                         "CrProgramShiftStatus",
	PropCameraLeverFunction:                        "CrCameraLeverFunction",
	PropMicrophoneDirectivity:                      "CrMicrophoneDirectivity",
	PropProductShowcaseSet:                         "CrProductShowcaseSet",
	PropCinematicVlogSetting:                       "CrCinematicVlogSetting",
	PropCinematicVlogLook:                          "CrCinematicVlogLook",
	PropCinematicVlogMood:                          "CrCinematicVlogMood",
	PropCinematicVlogAFTransitionSpeed:             "CrCinematicVlogAFTransitionSpeed",
	PropMonitoringTransportProtocol:                "CrMonitoringTransportProtocol",
	PropMonitoringOutputDisplaySDI:                 "CrMonitoringOutputDisplaySDI",
	PropFaceEyeDetectionAFStatus:                   "CrFaceEyeDetectionAFStatus",
	PropAutoFocusHold:                              "CrAutoFocusHold",
	PropPushAFModeSetting:                          "CrPushAFModeSetting",
	PropTouchFunctionInMF:                          "CrTouchFunctionInMF",
	PropPushAutoFocus:                              "CrPushAutoFocus",
	PropPushAGC:                                    "CrPushAGC",
	PropPushAutoIris:                               "CrPushAutoIris",
	PropNDFilterPresetSelect:                       "CrNDFilterPresetSelect",
	PropPushAutoNDFilter:                           "CrPushAutoNDFilter",
	PropWhiteBalanceOffsetSetting:                  "CrWhiteBalanceOffsetSetting",
	PropWhiteBalanceSwitch:                         "CrWhiteBalanceSwitch",
	PropPaintLookDetailSetting:                     "CrPaintLookDetailSetting",
	PropPaintLookAutoKnee:                          "CrPaintLookAutoKnee",
	PropPaintLookKneeSetting:                       "CrPaintLookKneeSetting",
	PropUserBaseLookOutput:                         "CrUserBaseLookOutput",
	PropMonitorLUTSettingOutputDestAssign:          "CrMonitorLUTSettingOutputDestAssign",
	PropSQModeSetting:                              "CrSQModeSetting",
	PropMovieQualityFullAutoMode:                   "CrMovieQualityFullAutoMode",
	PropFileSettingsCameraId:                       "CrFileSettingsCameraId",
	PropFileSettingsCameraPosition:                 "CrFileSettingsCameraPosition",
	PropImageStabilizationFramingStabilizer:        "CrImageStabilizationFramingStabilizer",
	PropExposureStep:                               "CrExposureStep",
	PropEnlargeScreenSetting:                       "CrEnlargeScreenSetting",
	PropPostViewTransferResourceStatus:             "CrPostViewTransferResourceStatus",
	PropSimulRecSetting:                            "CrSimulRecSetting",
	PropSimulRecSettingMovieRecButton:              "CrSimulRecSettingMovieRecButton",
	PropShutterSelectMode:                          "CrShutterSelectMode",
	PropOSDImageMode:                               "CrOSDImageMode",
	PropDebugMode:                                  "CrDebugMode",
	PropPanPositionStatus:                          "CrPanPositionStatus",
	PropTiltPositionStatus:                         "CrTiltPositionStatus",
	PropPanTiltAccelerationRampCurve:               "CrPanTiltAccelerationRampCurve",
	PropPanLimitMode:                               "CrPanLimitMode",
	PropTiltLimitMode:                              "CrTiltLimitMode",
	PropCameraPowerStatus:                          "CrCameraPowerStatus",
	PropStreamStatus:                               "CrStreamStatus",
	PropIRRemoteSetting:                            "CrIRRemoteSetting",
	PropIPSetupProtocolSetting:                     "CrIPSetupProtocolSetting",
	PropRecordablePowerSources:                     "CrRecordablePowerSources",
	PropStreamSettingListOperationStatus:           "CrStreamSettingListOperationStatus",
	PropPaintLookMultiMatrixAreaIndication:         "CrPaintLookMultiMatrixAreaIndication",
	PropIrisCloseSetting:                           "CrIrisCloseSetting",
	PropDisplayedMenuStatus:                        "CrDisplayedMenuStatus",
	PropLanguageSetting:                            "CrLanguageSetting",
	PropPlaybackContentsRecordingFrameRate:         "CrPlaybackContentsRecordingFrameRate",
	PropPlaybackContentsRecordingFileFormat:        "CrPlaybackContentsRecordingFileFormat",
	PropPlaybackContentsGammaType:                  "CrPlaybackContentsGammaType",
	PropBaseLookAppliedofPlayback:                  "CrBaseLookAppliedofPlayback",
	PropPaintLookMultiMatrixAxis:                   "CrPaintLookMultiMatrixAxis",
	PropFocusModeStatus:                            "CrFocusModeStatus",
	PropFocusOperationWithInt16EnableStatus:        "CrFocusOperationWithInt16EnableStatus",
	PropRemoteKeyThumbnailButton:                   "CrRemoteKeyThumbnailButton",
	PropRemoteKeySLOTSelectButton:                  "CrRemoteKeySLOTSelectButton",
	PropVideoRecordingFormatBitrateSetting:         "CrVideoRecordingFormatBitrateSetting",
	PropMonitoringOutputFormat:                     "CrMonitoringOutputFormat",
	PropVideoRecordingFormatQuality:                "CrVideoRecordingFormatQuality",
	PropPictureCacheRecSetting:                     "CrPictureCacheRecSetting",
	PropImagerScanMode:                             "CrImagerScanMode",
	PropShootingEnableSettingLicense:               "CrShootingEnableSettingLicense",
	PropGridLineType:                               "CrGridLineType",
	PropStreamButtonEnableStatus:                   "CrStreamButtonEnableStatus",
	PropDifferentSetForSQMovie:                     "CrDifferentSetForSQMovie",
	PropLogShootingMode:                            "CrLogShootingMode",
	PropLogShootingModeColorGamut:                  "CrLogShootingModeColorGamut",
	PropVideoStreamAdaptiveRateControl:             "CrVideoStreamAdaptiveRateControl",
	PropVideoStreamCodec:                           "CrVideoStreamCodec",
	PropStreamCipherType:                           "CrStreamCipherType",
	PropStreamModeSetting:                          "CrStreamModeSetting",
	PropVideoStreamResolutionMethod:                "CrVideoStreamResolutionMethod",
	PropVideoStreamMovieRecPermission:              "CrVideoStreamMovieRecPermission",
	PropVideoStreamBitRateCompressionMode:          "CrVideoStreamBitRateCompressionMode",
	PropVideoStreamBitRateVBRMode:                  "CrVideoStreamBitRateVBRMode",
	PropAudioStreamCodecType:                       "CrAudioStreamCodecType",
	PropAudioStreamBitDepth:                        "CrAudioStreamBitDepth",
	PropAudioStreamChannel:                         "CrAudioStreamChannel",
	PropHomeMenuSetting:                            "CrHomeMenuSetting",
	PropCallSetting:                                "CrCallSetting",
	PropEframingType:                               "CrEframingType",
	PropEframingAutoFraming:                        "CrEframingAutoFraming",
	PropEframingTrackingStartMode:                  "CrEframingTrackingStartMode",
	PropEframingProductionEffect:                   "CrEframingProductionEffect",
	PropTopOfTheGroupShootingMarkSetting:           "CrTopOfTheGroupShootingMarkSetting",
	PropMovieRecReviewPlayingState:                 "CrMovieRecReviewPlayingState",
	PropWindNoiseReductForExternalMic:              "CrWindNoiseReductForExternalMic",
	PropNoiseCutFilter:                             "CrNoiseCutFilter",
	PropNoiseCutFilterForExternalMic:               "CrNoiseCutFilterForExternalMic",
	PropCompRAWShootingHDRDRSetting:                "CrCompRAWShootingHDRDRSetting",
	PropControlGeneralSettingFileEnableStatus:      "CrControlGeneralSettingFileEnableStatus",
	PropPeakingDisplay:                             "CrPeakingDisplay",
	PropPeakingLevel:                               "CrPeakingLevel",
	PropPeakingColor:                               "CrPeakingColor",
	PropZebraDisplay:                               "CrZebraDisplay",
	PropZebraLevel:                                 "CrZebraLevel",
	PropZebraLevelTypeCustom:                       "CrZebraLevelTypeCustom",
	PropMarkerDisplay:                              "CrMarkerDisplay",
	PropCenterMarkerDisplay:                        "CrCenterMarkerDisplay",
	PropAspectMarkerRatioMovie:                     "CrAspectMarkerRatioMovie",
	PropSafetyZoneDisplay:                          "CrSafetyZoneDisplay",
	PropGuideframeDisplay:                          "CrGuideframeDisplay",
	PropDualGain:                                   "CrDualGain",
}
